// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/enrichment_service.proto

package datapower.noesis.v1;

/**
 * <pre>
 * Batch enrichment request for Flink
 * </pre>
 *
 * Protobuf type {@code datapower.noesis.v1.BatchFlinkEnrichmentRequest}
 */
public final class BatchFlinkEnrichmentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datapower.noesis.v1.BatchFlinkEnrichmentRequest)
    BatchFlinkEnrichmentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchFlinkEnrichmentRequest.newBuilder() to construct.
  private BatchFlinkEnrichmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchFlinkEnrichmentRequest() {
    requests_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatchFlinkEnrichmentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datapower.noesis.v1.FlinkEnrichmentServiceProto.internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datapower.noesis.v1.FlinkEnrichmentServiceProto.internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datapower.noesis.v1.BatchFlinkEnrichmentRequest.class, datapower.noesis.v1.BatchFlinkEnrichmentRequest.Builder.class);
  }

  public static final int REQUESTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<datapower.noesis.v1.EnrichmentRequest> requests_;
  /**
   * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
   */
  @java.lang.Override
  public java.util.List<datapower.noesis.v1.EnrichmentRequest> getRequestsList() {
    return requests_;
  }
  /**
   * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends datapower.noesis.v1.EnrichmentRequestOrBuilder> 
      getRequestsOrBuilderList() {
    return requests_;
  }
  /**
   * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
   */
  @java.lang.Override
  public int getRequestsCount() {
    return requests_.size();
  }
  /**
   * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.EnrichmentRequest getRequests(int index) {
    return requests_.get(index);
  }
  /**
   * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.EnrichmentRequestOrBuilder getRequestsOrBuilder(
      int index) {
    return requests_.get(index);
  }

  public static final int BATCH_ID_FIELD_NUMBER = 2;
  private int batchId_ = 0;
  /**
   * <pre>
   * Flink batch identifier
   * </pre>
   *
   * <code>int32 batch_id = 2 [json_name = "batchId"];</code>
   * @return The batchId.
   */
  @java.lang.Override
  public int getBatchId() {
    return batchId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < requests_.size(); i++) {
      output.writeMessage(1, requests_.get(i));
    }
    if (batchId_ != 0) {
      output.writeInt32(2, batchId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < requests_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, requests_.get(i));
    }
    if (batchId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, batchId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datapower.noesis.v1.BatchFlinkEnrichmentRequest)) {
      return super.equals(obj);
    }
    datapower.noesis.v1.BatchFlinkEnrichmentRequest other = (datapower.noesis.v1.BatchFlinkEnrichmentRequest) obj;

    if (!getRequestsList()
        .equals(other.getRequestsList())) return false;
    if (getBatchId()
        != other.getBatchId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRequestsCount() > 0) {
      hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestsList().hashCode();
    }
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datapower.noesis.v1.BatchFlinkEnrichmentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Batch enrichment request for Flink
   * </pre>
   *
   * Protobuf type {@code datapower.noesis.v1.BatchFlinkEnrichmentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datapower.noesis.v1.BatchFlinkEnrichmentRequest)
      datapower.noesis.v1.BatchFlinkEnrichmentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datapower.noesis.v1.FlinkEnrichmentServiceProto.internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datapower.noesis.v1.FlinkEnrichmentServiceProto.internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datapower.noesis.v1.BatchFlinkEnrichmentRequest.class, datapower.noesis.v1.BatchFlinkEnrichmentRequest.Builder.class);
    }

    // Construct using datapower.noesis.v1.BatchFlinkEnrichmentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (requestsBuilder_ == null) {
        requests_ = java.util.Collections.emptyList();
      } else {
        requests_ = null;
        requestsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      batchId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datapower.noesis.v1.FlinkEnrichmentServiceProto.internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor;
    }

    @java.lang.Override
    public datapower.noesis.v1.BatchFlinkEnrichmentRequest getDefaultInstanceForType() {
      return datapower.noesis.v1.BatchFlinkEnrichmentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public datapower.noesis.v1.BatchFlinkEnrichmentRequest build() {
      datapower.noesis.v1.BatchFlinkEnrichmentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public datapower.noesis.v1.BatchFlinkEnrichmentRequest buildPartial() {
      datapower.noesis.v1.BatchFlinkEnrichmentRequest result = new datapower.noesis.v1.BatchFlinkEnrichmentRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(datapower.noesis.v1.BatchFlinkEnrichmentRequest result) {
      if (requestsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          requests_ = java.util.Collections.unmodifiableList(requests_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.requests_ = requests_;
      } else {
        result.requests_ = requestsBuilder_.build();
      }
    }

    private void buildPartial0(datapower.noesis.v1.BatchFlinkEnrichmentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.batchId_ = batchId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datapower.noesis.v1.BatchFlinkEnrichmentRequest) {
        return mergeFrom((datapower.noesis.v1.BatchFlinkEnrichmentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datapower.noesis.v1.BatchFlinkEnrichmentRequest other) {
      if (other == datapower.noesis.v1.BatchFlinkEnrichmentRequest.getDefaultInstance()) return this;
      if (requestsBuilder_ == null) {
        if (!other.requests_.isEmpty()) {
          if (requests_.isEmpty()) {
            requests_ = other.requests_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRequestsIsMutable();
            requests_.addAll(other.requests_);
          }
          onChanged();
        }
      } else {
        if (!other.requests_.isEmpty()) {
          if (requestsBuilder_.isEmpty()) {
            requestsBuilder_.dispose();
            requestsBuilder_ = null;
            requests_ = other.requests_;
            bitField0_ = (bitField0_ & ~0x00000001);
            requestsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRequestsFieldBuilder() : null;
          } else {
            requestsBuilder_.addAllMessages(other.requests_);
          }
        }
      }
      if (other.getBatchId() != 0) {
        setBatchId(other.getBatchId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              datapower.noesis.v1.EnrichmentRequest m =
                  input.readMessage(
                      datapower.noesis.v1.EnrichmentRequest.parser(),
                      extensionRegistry);
              if (requestsBuilder_ == null) {
                ensureRequestsIsMutable();
                requests_.add(m);
              } else {
                requestsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              batchId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<datapower.noesis.v1.EnrichmentRequest> requests_ =
      java.util.Collections.emptyList();
    private void ensureRequestsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        requests_ = new java.util.ArrayList<datapower.noesis.v1.EnrichmentRequest>(requests_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.EnrichmentRequest, datapower.noesis.v1.EnrichmentRequest.Builder, datapower.noesis.v1.EnrichmentRequestOrBuilder> requestsBuilder_;

    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public java.util.List<datapower.noesis.v1.EnrichmentRequest> getRequestsList() {
      if (requestsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(requests_);
      } else {
        return requestsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public int getRequestsCount() {
      if (requestsBuilder_ == null) {
        return requests_.size();
      } else {
        return requestsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public datapower.noesis.v1.EnrichmentRequest getRequests(int index) {
      if (requestsBuilder_ == null) {
        return requests_.get(index);
      } else {
        return requestsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder setRequests(
        int index, datapower.noesis.v1.EnrichmentRequest value) {
      if (requestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestsIsMutable();
        requests_.set(index, value);
        onChanged();
      } else {
        requestsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder setRequests(
        int index, datapower.noesis.v1.EnrichmentRequest.Builder builderForValue) {
      if (requestsBuilder_ == null) {
        ensureRequestsIsMutable();
        requests_.set(index, builderForValue.build());
        onChanged();
      } else {
        requestsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder addRequests(datapower.noesis.v1.EnrichmentRequest value) {
      if (requestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestsIsMutable();
        requests_.add(value);
        onChanged();
      } else {
        requestsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder addRequests(
        int index, datapower.noesis.v1.EnrichmentRequest value) {
      if (requestsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestsIsMutable();
        requests_.add(index, value);
        onChanged();
      } else {
        requestsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder addRequests(
        datapower.noesis.v1.EnrichmentRequest.Builder builderForValue) {
      if (requestsBuilder_ == null) {
        ensureRequestsIsMutable();
        requests_.add(builderForValue.build());
        onChanged();
      } else {
        requestsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder addRequests(
        int index, datapower.noesis.v1.EnrichmentRequest.Builder builderForValue) {
      if (requestsBuilder_ == null) {
        ensureRequestsIsMutable();
        requests_.add(index, builderForValue.build());
        onChanged();
      } else {
        requestsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder addAllRequests(
        java.lang.Iterable<? extends datapower.noesis.v1.EnrichmentRequest> values) {
      if (requestsBuilder_ == null) {
        ensureRequestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requests_);
        onChanged();
      } else {
        requestsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder clearRequests() {
      if (requestsBuilder_ == null) {
        requests_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        requestsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public Builder removeRequests(int index) {
      if (requestsBuilder_ == null) {
        ensureRequestsIsMutable();
        requests_.remove(index);
        onChanged();
      } else {
        requestsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public datapower.noesis.v1.EnrichmentRequest.Builder getRequestsBuilder(
        int index) {
      return getRequestsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public datapower.noesis.v1.EnrichmentRequestOrBuilder getRequestsOrBuilder(
        int index) {
      if (requestsBuilder_ == null) {
        return requests_.get(index);  } else {
        return requestsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public java.util.List<? extends datapower.noesis.v1.EnrichmentRequestOrBuilder> 
         getRequestsOrBuilderList() {
      if (requestsBuilder_ != null) {
        return requestsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(requests_);
      }
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public datapower.noesis.v1.EnrichmentRequest.Builder addRequestsBuilder() {
      return getRequestsFieldBuilder().addBuilder(
          datapower.noesis.v1.EnrichmentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public datapower.noesis.v1.EnrichmentRequest.Builder addRequestsBuilder(
        int index) {
      return getRequestsFieldBuilder().addBuilder(
          index, datapower.noesis.v1.EnrichmentRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .datapower.noesis.v1.EnrichmentRequest requests = 1 [json_name = "requests"];</code>
     */
    public java.util.List<datapower.noesis.v1.EnrichmentRequest.Builder> 
         getRequestsBuilderList() {
      return getRequestsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.EnrichmentRequest, datapower.noesis.v1.EnrichmentRequest.Builder, datapower.noesis.v1.EnrichmentRequestOrBuilder> 
        getRequestsFieldBuilder() {
      if (requestsBuilder_ == null) {
        requestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datapower.noesis.v1.EnrichmentRequest, datapower.noesis.v1.EnrichmentRequest.Builder, datapower.noesis.v1.EnrichmentRequestOrBuilder>(
                requests_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        requests_ = null;
      }
      return requestsBuilder_;
    }

    private int batchId_ ;
    /**
     * <pre>
     * Flink batch identifier
     * </pre>
     *
     * <code>int32 batch_id = 2 [json_name = "batchId"];</code>
     * @return The batchId.
     */
    @java.lang.Override
    public int getBatchId() {
      return batchId_;
    }
    /**
     * <pre>
     * Flink batch identifier
     * </pre>
     *
     * <code>int32 batch_id = 2 [json_name = "batchId"];</code>
     * @param value The batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchId(int value) {

      batchId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Flink batch identifier
     * </pre>
     *
     * <code>int32 batch_id = 2 [json_name = "batchId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      batchId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datapower.noesis.v1.BatchFlinkEnrichmentRequest)
  }

  // @@protoc_insertion_point(class_scope:datapower.noesis.v1.BatchFlinkEnrichmentRequest)
  private static final datapower.noesis.v1.BatchFlinkEnrichmentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datapower.noesis.v1.BatchFlinkEnrichmentRequest();
  }

  public static datapower.noesis.v1.BatchFlinkEnrichmentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchFlinkEnrichmentRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchFlinkEnrichmentRequest>() {
    @java.lang.Override
    public BatchFlinkEnrichmentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchFlinkEnrichmentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchFlinkEnrichmentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public datapower.noesis.v1.BatchFlinkEnrichmentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

