// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/cdc_events.proto

package datapower.noesis.v1;

public interface CDCStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.CDCStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table = 1 [json_name = "table"];</code>
   * @return The table.
   */
  java.lang.String getTable();
  /**
   * <code>string table = 1 [json_name = "table"];</code>
   * @return The bytes for table.
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>int64 creates_count = 2 [json_name = "createsCount"];</code>
   * @return The createsCount.
   */
  long getCreatesCount();

  /**
   * <code>int64 updates_count = 3 [json_name = "updatesCount"];</code>
   * @return The updatesCount.
   */
  long getUpdatesCount();

  /**
   * <code>int64 deletes_count = 4 [json_name = "deletesCount"];</code>
   * @return The deletesCount.
   */
  long getDeletesCount();

  /**
   * <code>int64 unchanged_count = 5 [json_name = "unchangedCount"];</code>
   * @return The unchangedCount.
   */
  long getUnchangedCount();

  /**
   * <code>.google.protobuf.Timestamp period_start = 6 [json_name = "periodStart"];</code>
   * @return Whether the periodStart field is set.
   */
  boolean hasPeriodStart();
  /**
   * <code>.google.protobuf.Timestamp period_start = 6 [json_name = "periodStart"];</code>
   * @return The periodStart.
   */
  com.google.protobuf.Timestamp getPeriodStart();
  /**
   * <code>.google.protobuf.Timestamp period_start = 6 [json_name = "periodStart"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getPeriodStartOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp period_end = 7 [json_name = "periodEnd"];</code>
   * @return Whether the periodEnd field is set.
   */
  boolean hasPeriodEnd();
  /**
   * <code>.google.protobuf.Timestamp period_end = 7 [json_name = "periodEnd"];</code>
   * @return The periodEnd.
   */
  com.google.protobuf.Timestamp getPeriodEnd();
  /**
   * <code>.google.protobuf.Timestamp period_end = 7 [json_name = "periodEnd"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getPeriodEndOrBuilder();
}
