// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/connector.proto

package datapower.noesis.v1;

public interface CloseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.CloseResponse)
    com.google.protobuf.MessageOrBuilder {
}
