// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/sidecar.proto

package datapower.noesis.v1;

/**
 * <pre>
 * Delta Lake format configuration
 * </pre>
 *
 * Protobuf type {@code datapower.noesis.v1.DeltaConfig}
 */
public final class DeltaConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datapower.noesis.v1.DeltaConfig)
    DeltaConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeltaConfig.newBuilder() to construct.
  private DeltaConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeltaConfig() {
    tablePath_ = "";
    writeMode_ = 0;
    compression_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeltaConfig();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetTableProperties();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datapower.noesis.v1.DeltaConfig.class, datapower.noesis.v1.DeltaConfig.Builder.class);
  }

  public static final int TABLE_PATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tablePath_ = "";
  /**
   * <pre>
   * Delta table path (S3/GCS/HDFS path)
   * </pre>
   *
   * <code>string table_path = 1 [json_name = "tablePath"];</code>
   * @return The tablePath.
   */
  @java.lang.Override
  public java.lang.String getTablePath() {
    java.lang.Object ref = tablePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tablePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Delta table path (S3/GCS/HDFS path)
   * </pre>
   *
   * <code>string table_path = 1 [json_name = "tablePath"];</code>
   * @return The bytes for tablePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTablePathBytes() {
    java.lang.Object ref = tablePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tablePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WRITE_MODE_FIELD_NUMBER = 2;
  private int writeMode_ = 0;
  /**
   * <pre>
   * APPEND, MERGE, OVERWRITE
   * </pre>
   *
   * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
   * @return The enum numeric value on the wire for writeMode.
   */
  @java.lang.Override public int getWriteModeValue() {
    return writeMode_;
  }
  /**
   * <pre>
   * APPEND, MERGE, OVERWRITE
   * </pre>
   *
   * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
   * @return The writeMode.
   */
  @java.lang.Override public datapower.noesis.v1.WriteMode getWriteMode() {
    datapower.noesis.v1.WriteMode result = datapower.noesis.v1.WriteMode.forNumber(writeMode_);
    return result == null ? datapower.noesis.v1.WriteMode.UNRECOGNIZED : result;
  }

  public static final int COMPRESSION_FIELD_NUMBER = 3;
  private int compression_ = 0;
  /**
   * <pre>
   * Compression algorithm
   * </pre>
   *
   * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
   * @return The enum numeric value on the wire for compression.
   */
  @java.lang.Override public int getCompressionValue() {
    return compression_;
  }
  /**
   * <pre>
   * Compression algorithm
   * </pre>
   *
   * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
   * @return The compression.
   */
  @java.lang.Override public datapower.noesis.v1.CompressionCodec getCompression() {
    datapower.noesis.v1.CompressionCodec result = datapower.noesis.v1.CompressionCodec.forNumber(compression_);
    return result == null ? datapower.noesis.v1.CompressionCodec.UNRECOGNIZED : result;
  }

  public static final int TARGET_FILE_SIZE_BYTES_FIELD_NUMBER = 4;
  private long targetFileSizeBytes_ = 0L;
  /**
   * <pre>
   * Target data file size (default 128MB)
   * </pre>
   *
   * <code>int64 target_file_size_bytes = 4 [json_name = "targetFileSizeBytes"];</code>
   * @return The targetFileSizeBytes.
   */
  @java.lang.Override
  public long getTargetFileSizeBytes() {
    return targetFileSizeBytes_;
  }

  public static final int TABLE_PROPERTIES_FIELD_NUMBER = 5;
  private static final class TablePropertiesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_TablePropertiesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> tableProperties_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTableProperties() {
    if (tableProperties_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TablePropertiesDefaultEntryHolder.defaultEntry);
    }
    return tableProperties_;
  }
  public int getTablePropertiesCount() {
    return internalGetTableProperties().getMap().size();
  }
  /**
   * <pre>
   * Delta table properties
   * </pre>
   *
   * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
   */
  @java.lang.Override
  public boolean containsTableProperties(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTableProperties().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTablePropertiesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTableProperties() {
    return getTablePropertiesMap();
  }
  /**
   * <pre>
   * Delta table properties
   * </pre>
   *
   * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getTablePropertiesMap() {
    return internalGetTableProperties().getMap();
  }
  /**
   * <pre>
   * Delta table properties
   * </pre>
   *
   * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getTablePropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTableProperties().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Delta table properties
   * </pre>
   *
   * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
   */
  @java.lang.Override
  public java.lang.String getTablePropertiesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTableProperties().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tablePath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tablePath_);
    }
    if (writeMode_ != datapower.noesis.v1.WriteMode.WRITE_MODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, writeMode_);
    }
    if (compression_ != datapower.noesis.v1.CompressionCodec.COMPRESSION_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, compression_);
    }
    if (targetFileSizeBytes_ != 0L) {
      output.writeInt64(4, targetFileSizeBytes_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTableProperties(),
        TablePropertiesDefaultEntryHolder.defaultEntry,
        5);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tablePath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tablePath_);
    }
    if (writeMode_ != datapower.noesis.v1.WriteMode.WRITE_MODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, writeMode_);
    }
    if (compression_ != datapower.noesis.v1.CompressionCodec.COMPRESSION_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, compression_);
    }
    if (targetFileSizeBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, targetFileSizeBytes_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTableProperties().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      tableProperties__ = TablePropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, tableProperties__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datapower.noesis.v1.DeltaConfig)) {
      return super.equals(obj);
    }
    datapower.noesis.v1.DeltaConfig other = (datapower.noesis.v1.DeltaConfig) obj;

    if (!getTablePath()
        .equals(other.getTablePath())) return false;
    if (writeMode_ != other.writeMode_) return false;
    if (compression_ != other.compression_) return false;
    if (getTargetFileSizeBytes()
        != other.getTargetFileSizeBytes()) return false;
    if (!internalGetTableProperties().equals(
        other.internalGetTableProperties())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getTablePath().hashCode();
    hash = (37 * hash) + WRITE_MODE_FIELD_NUMBER;
    hash = (53 * hash) + writeMode_;
    hash = (37 * hash) + COMPRESSION_FIELD_NUMBER;
    hash = (53 * hash) + compression_;
    hash = (37 * hash) + TARGET_FILE_SIZE_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTargetFileSizeBytes());
    if (!internalGetTableProperties().getMap().isEmpty()) {
      hash = (37 * hash) + TABLE_PROPERTIES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTableProperties().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datapower.noesis.v1.DeltaConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static datapower.noesis.v1.DeltaConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static datapower.noesis.v1.DeltaConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.DeltaConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datapower.noesis.v1.DeltaConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Delta Lake format configuration
   * </pre>
   *
   * Protobuf type {@code datapower.noesis.v1.DeltaConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datapower.noesis.v1.DeltaConfig)
      datapower.noesis.v1.DeltaConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetTableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableTableProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datapower.noesis.v1.DeltaConfig.class, datapower.noesis.v1.DeltaConfig.Builder.class);
    }

    // Construct using datapower.noesis.v1.DeltaConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tablePath_ = "";
      writeMode_ = 0;
      compression_ = 0;
      targetFileSizeBytes_ = 0L;
      internalGetMutableTableProperties().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_DeltaConfig_descriptor;
    }

    @java.lang.Override
    public datapower.noesis.v1.DeltaConfig getDefaultInstanceForType() {
      return datapower.noesis.v1.DeltaConfig.getDefaultInstance();
    }

    @java.lang.Override
    public datapower.noesis.v1.DeltaConfig build() {
      datapower.noesis.v1.DeltaConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public datapower.noesis.v1.DeltaConfig buildPartial() {
      datapower.noesis.v1.DeltaConfig result = new datapower.noesis.v1.DeltaConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(datapower.noesis.v1.DeltaConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tablePath_ = tablePath_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.writeMode_ = writeMode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.compression_ = compression_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.targetFileSizeBytes_ = targetFileSizeBytes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tableProperties_ = internalGetTableProperties();
        result.tableProperties_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datapower.noesis.v1.DeltaConfig) {
        return mergeFrom((datapower.noesis.v1.DeltaConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datapower.noesis.v1.DeltaConfig other) {
      if (other == datapower.noesis.v1.DeltaConfig.getDefaultInstance()) return this;
      if (!other.getTablePath().isEmpty()) {
        tablePath_ = other.tablePath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.writeMode_ != 0) {
        setWriteModeValue(other.getWriteModeValue());
      }
      if (other.compression_ != 0) {
        setCompressionValue(other.getCompressionValue());
      }
      if (other.getTargetFileSizeBytes() != 0L) {
        setTargetFileSizeBytes(other.getTargetFileSizeBytes());
      }
      internalGetMutableTableProperties().mergeFrom(
          other.internalGetTableProperties());
      bitField0_ |= 0x00000010;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tablePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              writeMode_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              compression_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              targetFileSizeBytes_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tableProperties__ = input.readMessage(
                  TablePropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTableProperties().getMutableMap().put(
                  tableProperties__.getKey(), tableProperties__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tablePath_ = "";
    /**
     * <pre>
     * Delta table path (S3/GCS/HDFS path)
     * </pre>
     *
     * <code>string table_path = 1 [json_name = "tablePath"];</code>
     * @return The tablePath.
     */
    public java.lang.String getTablePath() {
      java.lang.Object ref = tablePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tablePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Delta table path (S3/GCS/HDFS path)
     * </pre>
     *
     * <code>string table_path = 1 [json_name = "tablePath"];</code>
     * @return The bytes for tablePath.
     */
    public com.google.protobuf.ByteString
        getTablePathBytes() {
      java.lang.Object ref = tablePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tablePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Delta table path (S3/GCS/HDFS path)
     * </pre>
     *
     * <code>string table_path = 1 [json_name = "tablePath"];</code>
     * @param value The tablePath to set.
     * @return This builder for chaining.
     */
    public Builder setTablePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tablePath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Delta table path (S3/GCS/HDFS path)
     * </pre>
     *
     * <code>string table_path = 1 [json_name = "tablePath"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTablePath() {
      tablePath_ = getDefaultInstance().getTablePath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Delta table path (S3/GCS/HDFS path)
     * </pre>
     *
     * <code>string table_path = 1 [json_name = "tablePath"];</code>
     * @param value The bytes for tablePath to set.
     * @return This builder for chaining.
     */
    public Builder setTablePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tablePath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int writeMode_ = 0;
    /**
     * <pre>
     * APPEND, MERGE, OVERWRITE
     * </pre>
     *
     * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
     * @return The enum numeric value on the wire for writeMode.
     */
    @java.lang.Override public int getWriteModeValue() {
      return writeMode_;
    }
    /**
     * <pre>
     * APPEND, MERGE, OVERWRITE
     * </pre>
     *
     * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
     * @param value The enum numeric value on the wire for writeMode to set.
     * @return This builder for chaining.
     */
    public Builder setWriteModeValue(int value) {
      writeMode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * APPEND, MERGE, OVERWRITE
     * </pre>
     *
     * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
     * @return The writeMode.
     */
    @java.lang.Override
    public datapower.noesis.v1.WriteMode getWriteMode() {
      datapower.noesis.v1.WriteMode result = datapower.noesis.v1.WriteMode.forNumber(writeMode_);
      return result == null ? datapower.noesis.v1.WriteMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * APPEND, MERGE, OVERWRITE
     * </pre>
     *
     * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
     * @param value The writeMode to set.
     * @return This builder for chaining.
     */
    public Builder setWriteMode(datapower.noesis.v1.WriteMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      writeMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * APPEND, MERGE, OVERWRITE
     * </pre>
     *
     * <code>.datapower.noesis.v1.WriteMode write_mode = 2 [json_name = "writeMode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteMode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      writeMode_ = 0;
      onChanged();
      return this;
    }

    private int compression_ = 0;
    /**
     * <pre>
     * Compression algorithm
     * </pre>
     *
     * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
     * @return The enum numeric value on the wire for compression.
     */
    @java.lang.Override public int getCompressionValue() {
      return compression_;
    }
    /**
     * <pre>
     * Compression algorithm
     * </pre>
     *
     * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
     * @param value The enum numeric value on the wire for compression to set.
     * @return This builder for chaining.
     */
    public Builder setCompressionValue(int value) {
      compression_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compression algorithm
     * </pre>
     *
     * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
     * @return The compression.
     */
    @java.lang.Override
    public datapower.noesis.v1.CompressionCodec getCompression() {
      datapower.noesis.v1.CompressionCodec result = datapower.noesis.v1.CompressionCodec.forNumber(compression_);
      return result == null ? datapower.noesis.v1.CompressionCodec.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Compression algorithm
     * </pre>
     *
     * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
     * @param value The compression to set.
     * @return This builder for chaining.
     */
    public Builder setCompression(datapower.noesis.v1.CompressionCodec value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      compression_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Compression algorithm
     * </pre>
     *
     * <code>.datapower.noesis.v1.CompressionCodec compression = 3 [json_name = "compression"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCompression() {
      bitField0_ = (bitField0_ & ~0x00000004);
      compression_ = 0;
      onChanged();
      return this;
    }

    private long targetFileSizeBytes_ ;
    /**
     * <pre>
     * Target data file size (default 128MB)
     * </pre>
     *
     * <code>int64 target_file_size_bytes = 4 [json_name = "targetFileSizeBytes"];</code>
     * @return The targetFileSizeBytes.
     */
    @java.lang.Override
    public long getTargetFileSizeBytes() {
      return targetFileSizeBytes_;
    }
    /**
     * <pre>
     * Target data file size (default 128MB)
     * </pre>
     *
     * <code>int64 target_file_size_bytes = 4 [json_name = "targetFileSizeBytes"];</code>
     * @param value The targetFileSizeBytes to set.
     * @return This builder for chaining.
     */
    public Builder setTargetFileSizeBytes(long value) {

      targetFileSizeBytes_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target data file size (default 128MB)
     * </pre>
     *
     * <code>int64 target_file_size_bytes = 4 [json_name = "targetFileSizeBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetFileSizeBytes() {
      bitField0_ = (bitField0_ & ~0x00000008);
      targetFileSizeBytes_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tableProperties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetTableProperties() {
      if (tableProperties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TablePropertiesDefaultEntryHolder.defaultEntry);
      }
      return tableProperties_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableTableProperties() {
      if (tableProperties_ == null) {
        tableProperties_ = com.google.protobuf.MapField.newMapField(
            TablePropertiesDefaultEntryHolder.defaultEntry);
      }
      if (!tableProperties_.isMutable()) {
        tableProperties_ = tableProperties_.copy();
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return tableProperties_;
    }
    public int getTablePropertiesCount() {
      return internalGetTableProperties().getMap().size();
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    @java.lang.Override
    public boolean containsTableProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTableProperties().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTablePropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTableProperties() {
      return getTablePropertiesMap();
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getTablePropertiesMap() {
      return internalGetTableProperties().getMap();
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getTablePropertiesOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTableProperties().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    @java.lang.Override
    public java.lang.String getTablePropertiesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTableProperties().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearTableProperties() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableTableProperties().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    public Builder removeTableProperties(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTableProperties().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableTableProperties() {
      bitField0_ |= 0x00000010;
      return internalGetMutableTableProperties().getMutableMap();
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    public Builder putTableProperties(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableTableProperties().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     * Delta table properties
     * </pre>
     *
     * <code>map&lt;string, string&gt; table_properties = 5 [json_name = "tableProperties"];</code>
     */
    public Builder putAllTableProperties(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTableProperties().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datapower.noesis.v1.DeltaConfig)
  }

  // @@protoc_insertion_point(class_scope:datapower.noesis.v1.DeltaConfig)
  private static final datapower.noesis.v1.DeltaConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datapower.noesis.v1.DeltaConfig();
  }

  public static datapower.noesis.v1.DeltaConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeltaConfig>
      PARSER = new com.google.protobuf.AbstractParser<DeltaConfig>() {
    @java.lang.Override
    public DeltaConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeltaConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeltaConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public datapower.noesis.v1.DeltaConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

