// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/execution.proto

package datapower.noesis.v1;

/**
 * <pre>
 * ExecutionResult captures the outcome of pipeline execution
 * </pre>
 *
 * Protobuf type {@code datapower.noesis.v1.ExecutionResult}
 */
public final class ExecutionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datapower.noesis.v1.ExecutionResult)
    ExecutionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutionResult.newBuilder() to construct.
  private ExecutionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutionResult() {
    pipelineName_ = "";
    executionId_ = "";
    mode_ = 0;
    status_ = 0;
    streamingJobResults_ = java.util.Collections.emptyList();
    extractionResults_ = java.util.Collections.emptyList();
    errorMessage_ = "";
    errorStackTrace_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecutionResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datapower.noesis.v1.Execution.internal_static_datapower_noesis_v1_ExecutionResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datapower.noesis.v1.Execution.internal_static_datapower_noesis_v1_ExecutionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datapower.noesis.v1.ExecutionResult.class, datapower.noesis.v1.ExecutionResult.Builder.class);
  }

  public static final int PIPELINE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pipelineName_ = "";
  /**
   * <pre>
   * Pipeline name
   * </pre>
   *
   * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
   * @return The pipelineName.
   */
  @java.lang.Override
  public java.lang.String getPipelineName() {
    java.lang.Object ref = pipelineName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pipelineName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pipeline name
   * </pre>
   *
   * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
   * @return The bytes for pipelineName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPipelineNameBytes() {
    java.lang.Object ref = pipelineName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pipelineName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXECUTION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object executionId_ = "";
  /**
   * <pre>
   * Execution ID (workflow run ID)
   * </pre>
   *
   * <code>string execution_id = 2 [json_name = "executionId"];</code>
   * @return The executionId.
   */
  @java.lang.Override
  public java.lang.String getExecutionId() {
    java.lang.Object ref = executionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      executionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Execution ID (workflow run ID)
   * </pre>
   *
   * <code>string execution_id = 2 [json_name = "executionId"];</code>
   * @return The bytes for executionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExecutionIdBytes() {
    java.lang.Object ref = executionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      executionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODE_FIELD_NUMBER = 3;
  private int mode_ = 0;
  /**
   * <pre>
   * Execution mode
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
   * @return The enum numeric value on the wire for mode.
   */
  @java.lang.Override public int getModeValue() {
    return mode_;
  }
  /**
   * <pre>
   * Execution mode
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
   * @return The mode.
   */
  @java.lang.Override public datapower.noesis.v1.ExecutionMode getMode() {
    datapower.noesis.v1.ExecutionMode result = datapower.noesis.v1.ExecutionMode.forNumber(mode_);
    return result == null ? datapower.noesis.v1.ExecutionMode.UNRECOGNIZED : result;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_ = 0;
  /**
   * <pre>
   * Overall status
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * Overall status
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public datapower.noesis.v1.ExecutionStatus getStatus() {
    datapower.noesis.v1.ExecutionStatus result = datapower.noesis.v1.ExecutionStatus.forNumber(status_);
    return result == null ? datapower.noesis.v1.ExecutionStatus.UNRECOGNIZED : result;
  }

  public static final int STARTED_AT_EPOCH_MS_FIELD_NUMBER = 5;
  private long startedAtEpochMs_ = 0L;
  /**
   * <pre>
   * Start and end times
   * </pre>
   *
   * <code>int64 started_at_epoch_ms = 5 [json_name = "startedAtEpochMs"];</code>
   * @return The startedAtEpochMs.
   */
  @java.lang.Override
  public long getStartedAtEpochMs() {
    return startedAtEpochMs_;
  }

  public static final int COMPLETED_AT_EPOCH_MS_FIELD_NUMBER = 6;
  private long completedAtEpochMs_ = 0L;
  /**
   * <code>int64 completed_at_epoch_ms = 6 [json_name = "completedAtEpochMs"];</code>
   * @return The completedAtEpochMs.
   */
  @java.lang.Override
  public long getCompletedAtEpochMs() {
    return completedAtEpochMs_;
  }

  public static final int DURATION_MS_FIELD_NUMBER = 7;
  private long durationMs_ = 0L;
  /**
   * <pre>
   * Duration in milliseconds
   * </pre>
   *
   * <code>int64 duration_ms = 7 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  @java.lang.Override
  public long getDurationMs() {
    return durationMs_;
  }

  public static final int STREAMING_JOB_RESULTS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<datapower.noesis.v1.StreamingJobResult> streamingJobResults_;
  /**
   * <pre>
   * Streaming job results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
   */
  @java.lang.Override
  public java.util.List<datapower.noesis.v1.StreamingJobResult> getStreamingJobResultsList() {
    return streamingJobResults_;
  }
  /**
   * <pre>
   * Streaming job results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends datapower.noesis.v1.StreamingJobResultOrBuilder> 
      getStreamingJobResultsOrBuilderList() {
    return streamingJobResults_;
  }
  /**
   * <pre>
   * Streaming job results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
   */
  @java.lang.Override
  public int getStreamingJobResultsCount() {
    return streamingJobResults_.size();
  }
  /**
   * <pre>
   * Streaming job results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.StreamingJobResult getStreamingJobResults(int index) {
    return streamingJobResults_.get(index);
  }
  /**
   * <pre>
   * Streaming job results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.StreamingJobResultOrBuilder getStreamingJobResultsOrBuilder(
      int index) {
    return streamingJobResults_.get(index);
  }

  public static final int EXTRACTION_RESULTS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<datapower.noesis.v1.ExtractionResult> extractionResults_;
  /**
   * <pre>
   * Batch extraction results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
   */
  @java.lang.Override
  public java.util.List<datapower.noesis.v1.ExtractionResult> getExtractionResultsList() {
    return extractionResults_;
  }
  /**
   * <pre>
   * Batch extraction results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends datapower.noesis.v1.ExtractionResultOrBuilder> 
      getExtractionResultsOrBuilderList() {
    return extractionResults_;
  }
  /**
   * <pre>
   * Batch extraction results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
   */
  @java.lang.Override
  public int getExtractionResultsCount() {
    return extractionResults_.size();
  }
  /**
   * <pre>
   * Batch extraction results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.ExtractionResult getExtractionResults(int index) {
    return extractionResults_.get(index);
  }
  /**
   * <pre>
   * Batch extraction results
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.ExtractionResultOrBuilder getExtractionResultsOrBuilder(
      int index) {
    return extractionResults_.get(index);
  }

  public static final int BATCH_RESULT_FIELD_NUMBER = 10;
  private datapower.noesis.v1.BatchJobResult batchResult_;
  /**
   * <pre>
   * Batch reconciliation result
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
   * @return Whether the batchResult field is set.
   */
  @java.lang.Override
  public boolean hasBatchResult() {
    return batchResult_ != null;
  }
  /**
   * <pre>
   * Batch reconciliation result
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
   * @return The batchResult.
   */
  @java.lang.Override
  public datapower.noesis.v1.BatchJobResult getBatchResult() {
    return batchResult_ == null ? datapower.noesis.v1.BatchJobResult.getDefaultInstance() : batchResult_;
  }
  /**
   * <pre>
   * Batch reconciliation result
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.BatchJobResultOrBuilder getBatchResultOrBuilder() {
    return batchResult_ == null ? datapower.noesis.v1.BatchJobResult.getDefaultInstance() : batchResult_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * Error information (if failed)
   * </pre>
   *
   * <code>string error_message = 11 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Error information (if failed)
   * </pre>
   *
   * <code>string error_message = 11 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_STACK_TRACE_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorStackTrace_ = "";
  /**
   * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
   * @return The errorStackTrace.
   */
  @java.lang.Override
  public java.lang.String getErrorStackTrace() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorStackTrace_ = s;
      return s;
    }
  }
  /**
   * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
   * @return The bytes for errorStackTrace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorStackTraceBytes() {
    java.lang.Object ref = errorStackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorStackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICS_FIELD_NUMBER = 13;
  private datapower.noesis.v1.ExecutionMetrics metrics_;
  /**
   * <pre>
   * Metrics
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
   * @return Whether the metrics field is set.
   */
  @java.lang.Override
  public boolean hasMetrics() {
    return metrics_ != null;
  }
  /**
   * <pre>
   * Metrics
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
   * @return The metrics.
   */
  @java.lang.Override
  public datapower.noesis.v1.ExecutionMetrics getMetrics() {
    return metrics_ == null ? datapower.noesis.v1.ExecutionMetrics.getDefaultInstance() : metrics_;
  }
  /**
   * <pre>
   * Metrics
   * </pre>
   *
   * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.ExecutionMetricsOrBuilder getMetricsOrBuilder() {
    return metrics_ == null ? datapower.noesis.v1.ExecutionMetrics.getDefaultInstance() : metrics_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pipelineName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(executionId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, executionId_);
    }
    if (mode_ != datapower.noesis.v1.ExecutionMode.EXECUTION_MODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, mode_);
    }
    if (status_ != datapower.noesis.v1.ExecutionStatus.EXECUTION_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (startedAtEpochMs_ != 0L) {
      output.writeInt64(5, startedAtEpochMs_);
    }
    if (completedAtEpochMs_ != 0L) {
      output.writeInt64(6, completedAtEpochMs_);
    }
    if (durationMs_ != 0L) {
      output.writeInt64(7, durationMs_);
    }
    for (int i = 0; i < streamingJobResults_.size(); i++) {
      output.writeMessage(8, streamingJobResults_.get(i));
    }
    for (int i = 0; i < extractionResults_.size(); i++) {
      output.writeMessage(9, extractionResults_.get(i));
    }
    if (batchResult_ != null) {
      output.writeMessage(10, getBatchResult());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, errorMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorStackTrace_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, errorStackTrace_);
    }
    if (metrics_ != null) {
      output.writeMessage(13, getMetrics());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pipelineName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(executionId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, executionId_);
    }
    if (mode_ != datapower.noesis.v1.ExecutionMode.EXECUTION_MODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, mode_);
    }
    if (status_ != datapower.noesis.v1.ExecutionStatus.EXECUTION_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (startedAtEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, startedAtEpochMs_);
    }
    if (completedAtEpochMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, completedAtEpochMs_);
    }
    if (durationMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, durationMs_);
    }
    for (int i = 0; i < streamingJobResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, streamingJobResults_.get(i));
    }
    for (int i = 0; i < extractionResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, extractionResults_.get(i));
    }
    if (batchResult_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getBatchResult());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, errorMessage_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorStackTrace_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, errorStackTrace_);
    }
    if (metrics_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getMetrics());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datapower.noesis.v1.ExecutionResult)) {
      return super.equals(obj);
    }
    datapower.noesis.v1.ExecutionResult other = (datapower.noesis.v1.ExecutionResult) obj;

    if (!getPipelineName()
        .equals(other.getPipelineName())) return false;
    if (!getExecutionId()
        .equals(other.getExecutionId())) return false;
    if (mode_ != other.mode_) return false;
    if (status_ != other.status_) return false;
    if (getStartedAtEpochMs()
        != other.getStartedAtEpochMs()) return false;
    if (getCompletedAtEpochMs()
        != other.getCompletedAtEpochMs()) return false;
    if (getDurationMs()
        != other.getDurationMs()) return false;
    if (!getStreamingJobResultsList()
        .equals(other.getStreamingJobResultsList())) return false;
    if (!getExtractionResultsList()
        .equals(other.getExtractionResultsList())) return false;
    if (hasBatchResult() != other.hasBatchResult()) return false;
    if (hasBatchResult()) {
      if (!getBatchResult()
          .equals(other.getBatchResult())) return false;
    }
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getErrorStackTrace()
        .equals(other.getErrorStackTrace())) return false;
    if (hasMetrics() != other.hasMetrics()) return false;
    if (hasMetrics()) {
      if (!getMetrics()
          .equals(other.getMetrics())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PIPELINE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPipelineName().hashCode();
    hash = (37 * hash) + EXECUTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExecutionId().hashCode();
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + mode_;
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + STARTED_AT_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartedAtEpochMs());
    hash = (37 * hash) + COMPLETED_AT_EPOCH_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCompletedAtEpochMs());
    hash = (37 * hash) + DURATION_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDurationMs());
    if (getStreamingJobResultsCount() > 0) {
      hash = (37 * hash) + STREAMING_JOB_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getStreamingJobResultsList().hashCode();
    }
    if (getExtractionResultsCount() > 0) {
      hash = (37 * hash) + EXTRACTION_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getExtractionResultsList().hashCode();
    }
    if (hasBatchResult()) {
      hash = (37 * hash) + BATCH_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getBatchResult().hashCode();
    }
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + ERROR_STACK_TRACE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorStackTrace().hashCode();
    if (hasMetrics()) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetrics().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datapower.noesis.v1.ExecutionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static datapower.noesis.v1.ExecutionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static datapower.noesis.v1.ExecutionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.ExecutionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datapower.noesis.v1.ExecutionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ExecutionResult captures the outcome of pipeline execution
   * </pre>
   *
   * Protobuf type {@code datapower.noesis.v1.ExecutionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datapower.noesis.v1.ExecutionResult)
      datapower.noesis.v1.ExecutionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datapower.noesis.v1.Execution.internal_static_datapower_noesis_v1_ExecutionResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datapower.noesis.v1.Execution.internal_static_datapower_noesis_v1_ExecutionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datapower.noesis.v1.ExecutionResult.class, datapower.noesis.v1.ExecutionResult.Builder.class);
    }

    // Construct using datapower.noesis.v1.ExecutionResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pipelineName_ = "";
      executionId_ = "";
      mode_ = 0;
      status_ = 0;
      startedAtEpochMs_ = 0L;
      completedAtEpochMs_ = 0L;
      durationMs_ = 0L;
      if (streamingJobResultsBuilder_ == null) {
        streamingJobResults_ = java.util.Collections.emptyList();
      } else {
        streamingJobResults_ = null;
        streamingJobResultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (extractionResultsBuilder_ == null) {
        extractionResults_ = java.util.Collections.emptyList();
      } else {
        extractionResults_ = null;
        extractionResultsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      batchResult_ = null;
      if (batchResultBuilder_ != null) {
        batchResultBuilder_.dispose();
        batchResultBuilder_ = null;
      }
      errorMessage_ = "";
      errorStackTrace_ = "";
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datapower.noesis.v1.Execution.internal_static_datapower_noesis_v1_ExecutionResult_descriptor;
    }

    @java.lang.Override
    public datapower.noesis.v1.ExecutionResult getDefaultInstanceForType() {
      return datapower.noesis.v1.ExecutionResult.getDefaultInstance();
    }

    @java.lang.Override
    public datapower.noesis.v1.ExecutionResult build() {
      datapower.noesis.v1.ExecutionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public datapower.noesis.v1.ExecutionResult buildPartial() {
      datapower.noesis.v1.ExecutionResult result = new datapower.noesis.v1.ExecutionResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(datapower.noesis.v1.ExecutionResult result) {
      if (streamingJobResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          streamingJobResults_ = java.util.Collections.unmodifiableList(streamingJobResults_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.streamingJobResults_ = streamingJobResults_;
      } else {
        result.streamingJobResults_ = streamingJobResultsBuilder_.build();
      }
      if (extractionResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0)) {
          extractionResults_ = java.util.Collections.unmodifiableList(extractionResults_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.extractionResults_ = extractionResults_;
      } else {
        result.extractionResults_ = extractionResultsBuilder_.build();
      }
    }

    private void buildPartial0(datapower.noesis.v1.ExecutionResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pipelineName_ = pipelineName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.executionId_ = executionId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mode_ = mode_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.startedAtEpochMs_ = startedAtEpochMs_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.completedAtEpochMs_ = completedAtEpochMs_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.durationMs_ = durationMs_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.batchResult_ = batchResultBuilder_ == null
            ? batchResult_
            : batchResultBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.errorStackTrace_ = errorStackTrace_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.metrics_ = metricsBuilder_ == null
            ? metrics_
            : metricsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datapower.noesis.v1.ExecutionResult) {
        return mergeFrom((datapower.noesis.v1.ExecutionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datapower.noesis.v1.ExecutionResult other) {
      if (other == datapower.noesis.v1.ExecutionResult.getDefaultInstance()) return this;
      if (!other.getPipelineName().isEmpty()) {
        pipelineName_ = other.pipelineName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getExecutionId().isEmpty()) {
        executionId_ = other.executionId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.mode_ != 0) {
        setModeValue(other.getModeValue());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getStartedAtEpochMs() != 0L) {
        setStartedAtEpochMs(other.getStartedAtEpochMs());
      }
      if (other.getCompletedAtEpochMs() != 0L) {
        setCompletedAtEpochMs(other.getCompletedAtEpochMs());
      }
      if (other.getDurationMs() != 0L) {
        setDurationMs(other.getDurationMs());
      }
      if (streamingJobResultsBuilder_ == null) {
        if (!other.streamingJobResults_.isEmpty()) {
          if (streamingJobResults_.isEmpty()) {
            streamingJobResults_ = other.streamingJobResults_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureStreamingJobResultsIsMutable();
            streamingJobResults_.addAll(other.streamingJobResults_);
          }
          onChanged();
        }
      } else {
        if (!other.streamingJobResults_.isEmpty()) {
          if (streamingJobResultsBuilder_.isEmpty()) {
            streamingJobResultsBuilder_.dispose();
            streamingJobResultsBuilder_ = null;
            streamingJobResults_ = other.streamingJobResults_;
            bitField0_ = (bitField0_ & ~0x00000080);
            streamingJobResultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStreamingJobResultsFieldBuilder() : null;
          } else {
            streamingJobResultsBuilder_.addAllMessages(other.streamingJobResults_);
          }
        }
      }
      if (extractionResultsBuilder_ == null) {
        if (!other.extractionResults_.isEmpty()) {
          if (extractionResults_.isEmpty()) {
            extractionResults_ = other.extractionResults_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureExtractionResultsIsMutable();
            extractionResults_.addAll(other.extractionResults_);
          }
          onChanged();
        }
      } else {
        if (!other.extractionResults_.isEmpty()) {
          if (extractionResultsBuilder_.isEmpty()) {
            extractionResultsBuilder_.dispose();
            extractionResultsBuilder_ = null;
            extractionResults_ = other.extractionResults_;
            bitField0_ = (bitField0_ & ~0x00000100);
            extractionResultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExtractionResultsFieldBuilder() : null;
          } else {
            extractionResultsBuilder_.addAllMessages(other.extractionResults_);
          }
        }
      }
      if (other.hasBatchResult()) {
        mergeBatchResult(other.getBatchResult());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getErrorStackTrace().isEmpty()) {
        errorStackTrace_ = other.errorStackTrace_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (other.hasMetrics()) {
        mergeMetrics(other.getMetrics());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pipelineName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              executionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              mode_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              startedAtEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              completedAtEpochMs_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              durationMs_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              datapower.noesis.v1.StreamingJobResult m =
                  input.readMessage(
                      datapower.noesis.v1.StreamingJobResult.parser(),
                      extensionRegistry);
              if (streamingJobResultsBuilder_ == null) {
                ensureStreamingJobResultsIsMutable();
                streamingJobResults_.add(m);
              } else {
                streamingJobResultsBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              datapower.noesis.v1.ExtractionResult m =
                  input.readMessage(
                      datapower.noesis.v1.ExtractionResult.parser(),
                      extensionRegistry);
              if (extractionResultsBuilder_ == null) {
                ensureExtractionResultsIsMutable();
                extractionResults_.add(m);
              } else {
                extractionResultsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getBatchResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              errorStackTrace_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getMetricsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object pipelineName_ = "";
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
     * @return The pipelineName.
     */
    public java.lang.String getPipelineName() {
      java.lang.Object ref = pipelineName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipelineName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
     * @return The bytes for pipelineName.
     */
    public com.google.protobuf.ByteString
        getPipelineNameBytes() {
      java.lang.Object ref = pipelineName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipelineName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
     * @param value The pipelineName to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pipelineName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPipelineName() {
      pipelineName_ = getDefaultInstance().getPipelineName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 1 [json_name = "pipelineName"];</code>
     * @param value The bytes for pipelineName to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pipelineName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object executionId_ = "";
    /**
     * <pre>
     * Execution ID (workflow run ID)
     * </pre>
     *
     * <code>string execution_id = 2 [json_name = "executionId"];</code>
     * @return The executionId.
     */
    public java.lang.String getExecutionId() {
      java.lang.Object ref = executionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        executionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Execution ID (workflow run ID)
     * </pre>
     *
     * <code>string execution_id = 2 [json_name = "executionId"];</code>
     * @return The bytes for executionId.
     */
    public com.google.protobuf.ByteString
        getExecutionIdBytes() {
      java.lang.Object ref = executionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        executionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Execution ID (workflow run ID)
     * </pre>
     *
     * <code>string execution_id = 2 [json_name = "executionId"];</code>
     * @param value The executionId to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      executionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution ID (workflow run ID)
     * </pre>
     *
     * <code>string execution_id = 2 [json_name = "executionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionId() {
      executionId_ = getDefaultInstance().getExecutionId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution ID (workflow run ID)
     * </pre>
     *
     * <code>string execution_id = 2 [json_name = "executionId"];</code>
     * @param value The bytes for executionId to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      executionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int mode_ = 0;
    /**
     * <pre>
     * Execution mode
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
     * @return The enum numeric value on the wire for mode.
     */
    @java.lang.Override public int getModeValue() {
      return mode_;
    }
    /**
     * <pre>
     * Execution mode
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
     * @param value The enum numeric value on the wire for mode to set.
     * @return This builder for chaining.
     */
    public Builder setModeValue(int value) {
      mode_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution mode
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
     * @return The mode.
     */
    @java.lang.Override
    public datapower.noesis.v1.ExecutionMode getMode() {
      datapower.noesis.v1.ExecutionMode result = datapower.noesis.v1.ExecutionMode.forNumber(mode_);
      return result == null ? datapower.noesis.v1.ExecutionMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Execution mode
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
     * @param value The mode to set.
     * @return This builder for chaining.
     */
    public Builder setMode(datapower.noesis.v1.ExecutionMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      mode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Execution mode
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMode mode = 3 [json_name = "mode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mode_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * Overall status
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * Overall status
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Overall status
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public datapower.noesis.v1.ExecutionStatus getStatus() {
      datapower.noesis.v1.ExecutionStatus result = datapower.noesis.v1.ExecutionStatus.forNumber(status_);
      return result == null ? datapower.noesis.v1.ExecutionStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Overall status
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(datapower.noesis.v1.ExecutionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Overall status
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionStatus status = 4 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private long startedAtEpochMs_ ;
    /**
     * <pre>
     * Start and end times
     * </pre>
     *
     * <code>int64 started_at_epoch_ms = 5 [json_name = "startedAtEpochMs"];</code>
     * @return The startedAtEpochMs.
     */
    @java.lang.Override
    public long getStartedAtEpochMs() {
      return startedAtEpochMs_;
    }
    /**
     * <pre>
     * Start and end times
     * </pre>
     *
     * <code>int64 started_at_epoch_ms = 5 [json_name = "startedAtEpochMs"];</code>
     * @param value The startedAtEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setStartedAtEpochMs(long value) {

      startedAtEpochMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start and end times
     * </pre>
     *
     * <code>int64 started_at_epoch_ms = 5 [json_name = "startedAtEpochMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedAtEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      startedAtEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private long completedAtEpochMs_ ;
    /**
     * <code>int64 completed_at_epoch_ms = 6 [json_name = "completedAtEpochMs"];</code>
     * @return The completedAtEpochMs.
     */
    @java.lang.Override
    public long getCompletedAtEpochMs() {
      return completedAtEpochMs_;
    }
    /**
     * <code>int64 completed_at_epoch_ms = 6 [json_name = "completedAtEpochMs"];</code>
     * @param value The completedAtEpochMs to set.
     * @return This builder for chaining.
     */
    public Builder setCompletedAtEpochMs(long value) {

      completedAtEpochMs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 completed_at_epoch_ms = 6 [json_name = "completedAtEpochMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCompletedAtEpochMs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      completedAtEpochMs_ = 0L;
      onChanged();
      return this;
    }

    private long durationMs_ ;
    /**
     * <pre>
     * Duration in milliseconds
     * </pre>
     *
     * <code>int64 duration_ms = 7 [json_name = "durationMs"];</code>
     * @return The durationMs.
     */
    @java.lang.Override
    public long getDurationMs() {
      return durationMs_;
    }
    /**
     * <pre>
     * Duration in milliseconds
     * </pre>
     *
     * <code>int64 duration_ms = 7 [json_name = "durationMs"];</code>
     * @param value The durationMs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMs(long value) {

      durationMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Duration in milliseconds
     * </pre>
     *
     * <code>int64 duration_ms = 7 [json_name = "durationMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      durationMs_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<datapower.noesis.v1.StreamingJobResult> streamingJobResults_ =
      java.util.Collections.emptyList();
    private void ensureStreamingJobResultsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        streamingJobResults_ = new java.util.ArrayList<datapower.noesis.v1.StreamingJobResult>(streamingJobResults_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.StreamingJobResult, datapower.noesis.v1.StreamingJobResult.Builder, datapower.noesis.v1.StreamingJobResultOrBuilder> streamingJobResultsBuilder_;

    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public java.util.List<datapower.noesis.v1.StreamingJobResult> getStreamingJobResultsList() {
      if (streamingJobResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(streamingJobResults_);
      } else {
        return streamingJobResultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public int getStreamingJobResultsCount() {
      if (streamingJobResultsBuilder_ == null) {
        return streamingJobResults_.size();
      } else {
        return streamingJobResultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public datapower.noesis.v1.StreamingJobResult getStreamingJobResults(int index) {
      if (streamingJobResultsBuilder_ == null) {
        return streamingJobResults_.get(index);
      } else {
        return streamingJobResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder setStreamingJobResults(
        int index, datapower.noesis.v1.StreamingJobResult value) {
      if (streamingJobResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.set(index, value);
        onChanged();
      } else {
        streamingJobResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder setStreamingJobResults(
        int index, datapower.noesis.v1.StreamingJobResult.Builder builderForValue) {
      if (streamingJobResultsBuilder_ == null) {
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        streamingJobResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder addStreamingJobResults(datapower.noesis.v1.StreamingJobResult value) {
      if (streamingJobResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.add(value);
        onChanged();
      } else {
        streamingJobResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder addStreamingJobResults(
        int index, datapower.noesis.v1.StreamingJobResult value) {
      if (streamingJobResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.add(index, value);
        onChanged();
      } else {
        streamingJobResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder addStreamingJobResults(
        datapower.noesis.v1.StreamingJobResult.Builder builderForValue) {
      if (streamingJobResultsBuilder_ == null) {
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.add(builderForValue.build());
        onChanged();
      } else {
        streamingJobResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder addStreamingJobResults(
        int index, datapower.noesis.v1.StreamingJobResult.Builder builderForValue) {
      if (streamingJobResultsBuilder_ == null) {
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        streamingJobResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder addAllStreamingJobResults(
        java.lang.Iterable<? extends datapower.noesis.v1.StreamingJobResult> values) {
      if (streamingJobResultsBuilder_ == null) {
        ensureStreamingJobResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, streamingJobResults_);
        onChanged();
      } else {
        streamingJobResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder clearStreamingJobResults() {
      if (streamingJobResultsBuilder_ == null) {
        streamingJobResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        streamingJobResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public Builder removeStreamingJobResults(int index) {
      if (streamingJobResultsBuilder_ == null) {
        ensureStreamingJobResultsIsMutable();
        streamingJobResults_.remove(index);
        onChanged();
      } else {
        streamingJobResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public datapower.noesis.v1.StreamingJobResult.Builder getStreamingJobResultsBuilder(
        int index) {
      return getStreamingJobResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public datapower.noesis.v1.StreamingJobResultOrBuilder getStreamingJobResultsOrBuilder(
        int index) {
      if (streamingJobResultsBuilder_ == null) {
        return streamingJobResults_.get(index);  } else {
        return streamingJobResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public java.util.List<? extends datapower.noesis.v1.StreamingJobResultOrBuilder> 
         getStreamingJobResultsOrBuilderList() {
      if (streamingJobResultsBuilder_ != null) {
        return streamingJobResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(streamingJobResults_);
      }
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public datapower.noesis.v1.StreamingJobResult.Builder addStreamingJobResultsBuilder() {
      return getStreamingJobResultsFieldBuilder().addBuilder(
          datapower.noesis.v1.StreamingJobResult.getDefaultInstance());
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public datapower.noesis.v1.StreamingJobResult.Builder addStreamingJobResultsBuilder(
        int index) {
      return getStreamingJobResultsFieldBuilder().addBuilder(
          index, datapower.noesis.v1.StreamingJobResult.getDefaultInstance());
    }
    /**
     * <pre>
     * Streaming job results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.StreamingJobResult streaming_job_results = 8 [json_name = "streamingJobResults"];</code>
     */
    public java.util.List<datapower.noesis.v1.StreamingJobResult.Builder> 
         getStreamingJobResultsBuilderList() {
      return getStreamingJobResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.StreamingJobResult, datapower.noesis.v1.StreamingJobResult.Builder, datapower.noesis.v1.StreamingJobResultOrBuilder> 
        getStreamingJobResultsFieldBuilder() {
      if (streamingJobResultsBuilder_ == null) {
        streamingJobResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datapower.noesis.v1.StreamingJobResult, datapower.noesis.v1.StreamingJobResult.Builder, datapower.noesis.v1.StreamingJobResultOrBuilder>(
                streamingJobResults_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        streamingJobResults_ = null;
      }
      return streamingJobResultsBuilder_;
    }

    private java.util.List<datapower.noesis.v1.ExtractionResult> extractionResults_ =
      java.util.Collections.emptyList();
    private void ensureExtractionResultsIsMutable() {
      if (!((bitField0_ & 0x00000100) != 0)) {
        extractionResults_ = new java.util.ArrayList<datapower.noesis.v1.ExtractionResult>(extractionResults_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.ExtractionResult, datapower.noesis.v1.ExtractionResult.Builder, datapower.noesis.v1.ExtractionResultOrBuilder> extractionResultsBuilder_;

    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public java.util.List<datapower.noesis.v1.ExtractionResult> getExtractionResultsList() {
      if (extractionResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(extractionResults_);
      } else {
        return extractionResultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public int getExtractionResultsCount() {
      if (extractionResultsBuilder_ == null) {
        return extractionResults_.size();
      } else {
        return extractionResultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public datapower.noesis.v1.ExtractionResult getExtractionResults(int index) {
      if (extractionResultsBuilder_ == null) {
        return extractionResults_.get(index);
      } else {
        return extractionResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder setExtractionResults(
        int index, datapower.noesis.v1.ExtractionResult value) {
      if (extractionResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtractionResultsIsMutable();
        extractionResults_.set(index, value);
        onChanged();
      } else {
        extractionResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder setExtractionResults(
        int index, datapower.noesis.v1.ExtractionResult.Builder builderForValue) {
      if (extractionResultsBuilder_ == null) {
        ensureExtractionResultsIsMutable();
        extractionResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        extractionResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder addExtractionResults(datapower.noesis.v1.ExtractionResult value) {
      if (extractionResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtractionResultsIsMutable();
        extractionResults_.add(value);
        onChanged();
      } else {
        extractionResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder addExtractionResults(
        int index, datapower.noesis.v1.ExtractionResult value) {
      if (extractionResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExtractionResultsIsMutable();
        extractionResults_.add(index, value);
        onChanged();
      } else {
        extractionResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder addExtractionResults(
        datapower.noesis.v1.ExtractionResult.Builder builderForValue) {
      if (extractionResultsBuilder_ == null) {
        ensureExtractionResultsIsMutable();
        extractionResults_.add(builderForValue.build());
        onChanged();
      } else {
        extractionResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder addExtractionResults(
        int index, datapower.noesis.v1.ExtractionResult.Builder builderForValue) {
      if (extractionResultsBuilder_ == null) {
        ensureExtractionResultsIsMutable();
        extractionResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        extractionResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder addAllExtractionResults(
        java.lang.Iterable<? extends datapower.noesis.v1.ExtractionResult> values) {
      if (extractionResultsBuilder_ == null) {
        ensureExtractionResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, extractionResults_);
        onChanged();
      } else {
        extractionResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder clearExtractionResults() {
      if (extractionResultsBuilder_ == null) {
        extractionResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        extractionResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public Builder removeExtractionResults(int index) {
      if (extractionResultsBuilder_ == null) {
        ensureExtractionResultsIsMutable();
        extractionResults_.remove(index);
        onChanged();
      } else {
        extractionResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public datapower.noesis.v1.ExtractionResult.Builder getExtractionResultsBuilder(
        int index) {
      return getExtractionResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public datapower.noesis.v1.ExtractionResultOrBuilder getExtractionResultsOrBuilder(
        int index) {
      if (extractionResultsBuilder_ == null) {
        return extractionResults_.get(index);  } else {
        return extractionResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public java.util.List<? extends datapower.noesis.v1.ExtractionResultOrBuilder> 
         getExtractionResultsOrBuilderList() {
      if (extractionResultsBuilder_ != null) {
        return extractionResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(extractionResults_);
      }
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public datapower.noesis.v1.ExtractionResult.Builder addExtractionResultsBuilder() {
      return getExtractionResultsFieldBuilder().addBuilder(
          datapower.noesis.v1.ExtractionResult.getDefaultInstance());
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public datapower.noesis.v1.ExtractionResult.Builder addExtractionResultsBuilder(
        int index) {
      return getExtractionResultsFieldBuilder().addBuilder(
          index, datapower.noesis.v1.ExtractionResult.getDefaultInstance());
    }
    /**
     * <pre>
     * Batch extraction results
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.ExtractionResult extraction_results = 9 [json_name = "extractionResults"];</code>
     */
    public java.util.List<datapower.noesis.v1.ExtractionResult.Builder> 
         getExtractionResultsBuilderList() {
      return getExtractionResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.ExtractionResult, datapower.noesis.v1.ExtractionResult.Builder, datapower.noesis.v1.ExtractionResultOrBuilder> 
        getExtractionResultsFieldBuilder() {
      if (extractionResultsBuilder_ == null) {
        extractionResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datapower.noesis.v1.ExtractionResult, datapower.noesis.v1.ExtractionResult.Builder, datapower.noesis.v1.ExtractionResultOrBuilder>(
                extractionResults_,
                ((bitField0_ & 0x00000100) != 0),
                getParentForChildren(),
                isClean());
        extractionResults_ = null;
      }
      return extractionResultsBuilder_;
    }

    private datapower.noesis.v1.BatchJobResult batchResult_;
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.BatchJobResult, datapower.noesis.v1.BatchJobResult.Builder, datapower.noesis.v1.BatchJobResultOrBuilder> batchResultBuilder_;
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     * @return Whether the batchResult field is set.
     */
    public boolean hasBatchResult() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     * @return The batchResult.
     */
    public datapower.noesis.v1.BatchJobResult getBatchResult() {
      if (batchResultBuilder_ == null) {
        return batchResult_ == null ? datapower.noesis.v1.BatchJobResult.getDefaultInstance() : batchResult_;
      } else {
        return batchResultBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public Builder setBatchResult(datapower.noesis.v1.BatchJobResult value) {
      if (batchResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        batchResult_ = value;
      } else {
        batchResultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public Builder setBatchResult(
        datapower.noesis.v1.BatchJobResult.Builder builderForValue) {
      if (batchResultBuilder_ == null) {
        batchResult_ = builderForValue.build();
      } else {
        batchResultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public Builder mergeBatchResult(datapower.noesis.v1.BatchJobResult value) {
      if (batchResultBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          batchResult_ != null &&
          batchResult_ != datapower.noesis.v1.BatchJobResult.getDefaultInstance()) {
          getBatchResultBuilder().mergeFrom(value);
        } else {
          batchResult_ = value;
        }
      } else {
        batchResultBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public Builder clearBatchResult() {
      bitField0_ = (bitField0_ & ~0x00000200);
      batchResult_ = null;
      if (batchResultBuilder_ != null) {
        batchResultBuilder_.dispose();
        batchResultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public datapower.noesis.v1.BatchJobResult.Builder getBatchResultBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getBatchResultFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    public datapower.noesis.v1.BatchJobResultOrBuilder getBatchResultOrBuilder() {
      if (batchResultBuilder_ != null) {
        return batchResultBuilder_.getMessageOrBuilder();
      } else {
        return batchResult_ == null ?
            datapower.noesis.v1.BatchJobResult.getDefaultInstance() : batchResult_;
      }
    }
    /**
     * <pre>
     * Batch reconciliation result
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchJobResult batch_result = 10 [json_name = "batchResult"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.BatchJobResult, datapower.noesis.v1.BatchJobResult.Builder, datapower.noesis.v1.BatchJobResultOrBuilder> 
        getBatchResultFieldBuilder() {
      if (batchResultBuilder_ == null) {
        batchResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datapower.noesis.v1.BatchJobResult, datapower.noesis.v1.BatchJobResult.Builder, datapower.noesis.v1.BatchJobResultOrBuilder>(
                getBatchResult(),
                getParentForChildren(),
                isClean());
        batchResult_ = null;
      }
      return batchResultBuilder_;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * Error information (if failed)
     * </pre>
     *
     * <code>string error_message = 11 [json_name = "errorMessage"];</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Error information (if failed)
     * </pre>
     *
     * <code>string error_message = 11 [json_name = "errorMessage"];</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Error information (if failed)
     * </pre>
     *
     * <code>string error_message = 11 [json_name = "errorMessage"];</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error information (if failed)
     * </pre>
     *
     * <code>string error_message = 11 [json_name = "errorMessage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error information (if failed)
     * </pre>
     *
     * <code>string error_message = 11 [json_name = "errorMessage"];</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object errorStackTrace_ = "";
    /**
     * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
     * @return The errorStackTrace.
     */
    public java.lang.String getErrorStackTrace() {
      java.lang.Object ref = errorStackTrace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorStackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
     * @return The bytes for errorStackTrace.
     */
    public com.google.protobuf.ByteString
        getErrorStackTraceBytes() {
      java.lang.Object ref = errorStackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorStackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
     * @param value The errorStackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setErrorStackTrace(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorStackTrace_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorStackTrace() {
      errorStackTrace_ = getDefaultInstance().getErrorStackTrace();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string error_stack_trace = 12 [json_name = "errorStackTrace"];</code>
     * @param value The bytes for errorStackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setErrorStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorStackTrace_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private datapower.noesis.v1.ExecutionMetrics metrics_;
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.ExecutionMetrics, datapower.noesis.v1.ExecutionMetrics.Builder, datapower.noesis.v1.ExecutionMetricsOrBuilder> metricsBuilder_;
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     * @return Whether the metrics field is set.
     */
    public boolean hasMetrics() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     * @return The metrics.
     */
    public datapower.noesis.v1.ExecutionMetrics getMetrics() {
      if (metricsBuilder_ == null) {
        return metrics_ == null ? datapower.noesis.v1.ExecutionMetrics.getDefaultInstance() : metrics_;
      } else {
        return metricsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public Builder setMetrics(datapower.noesis.v1.ExecutionMetrics value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metrics_ = value;
      } else {
        metricsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public Builder setMetrics(
        datapower.noesis.v1.ExecutionMetrics.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        metrics_ = builderForValue.build();
      } else {
        metricsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public Builder mergeMetrics(datapower.noesis.v1.ExecutionMetrics value) {
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          metrics_ != null &&
          metrics_ != datapower.noesis.v1.ExecutionMetrics.getDefaultInstance()) {
          getMetricsBuilder().mergeFrom(value);
        } else {
          metrics_ = value;
        }
      } else {
        metricsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public Builder clearMetrics() {
      bitField0_ = (bitField0_ & ~0x00001000);
      metrics_ = null;
      if (metricsBuilder_ != null) {
        metricsBuilder_.dispose();
        metricsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public datapower.noesis.v1.ExecutionMetrics.Builder getMetricsBuilder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return getMetricsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    public datapower.noesis.v1.ExecutionMetricsOrBuilder getMetricsOrBuilder() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilder();
      } else {
        return metrics_ == null ?
            datapower.noesis.v1.ExecutionMetrics.getDefaultInstance() : metrics_;
      }
    }
    /**
     * <pre>
     * Metrics
     * </pre>
     *
     * <code>.datapower.noesis.v1.ExecutionMetrics metrics = 13 [json_name = "metrics"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.ExecutionMetrics, datapower.noesis.v1.ExecutionMetrics.Builder, datapower.noesis.v1.ExecutionMetricsOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datapower.noesis.v1.ExecutionMetrics, datapower.noesis.v1.ExecutionMetrics.Builder, datapower.noesis.v1.ExecutionMetricsOrBuilder>(
                getMetrics(),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datapower.noesis.v1.ExecutionResult)
  }

  // @@protoc_insertion_point(class_scope:datapower.noesis.v1.ExecutionResult)
  private static final datapower.noesis.v1.ExecutionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datapower.noesis.v1.ExecutionResult();
  }

  public static datapower.noesis.v1.ExecutionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutionResult>
      PARSER = new com.google.protobuf.AbstractParser<ExecutionResult>() {
    @java.lang.Override
    public ExecutionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecutionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutionResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public datapower.noesis.v1.ExecutionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

