// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/execution.proto

package datapower.noesis.v1;

public interface ExtractionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.ExtractionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string split_id = 1 [json_name = "splitId"];</code>
   * @return The splitId.
   */
  java.lang.String getSplitId();
  /**
   * <code>string split_id = 1 [json_name = "splitId"];</code>
   * @return The bytes for splitId.
   */
  com.google.protobuf.ByteString
      getSplitIdBytes();

  /**
   * <code>string source_alias = 2 [json_name = "sourceAlias"];</code>
   * @return The sourceAlias.
   */
  java.lang.String getSourceAlias();
  /**
   * <code>string source_alias = 2 [json_name = "sourceAlias"];</code>
   * @return The bytes for sourceAlias.
   */
  com.google.protobuf.ByteString
      getSourceAliasBytes();

  /**
   * <code>bool success = 3 [json_name = "success"];</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int64 rows_extracted = 4 [json_name = "rowsExtracted"];</code>
   * @return The rowsExtracted.
   */
  long getRowsExtracted();

  /**
   * <code>int64 bytes_written = 5 [json_name = "bytesWritten"];</code>
   * @return The bytesWritten.
   */
  long getBytesWritten();

  /**
   * <code>int64 duration_ms = 6 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  long getDurationMs();

  /**
   * <code>string error_message = 7 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 7 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
