// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/enrichment_service.proto

package datapower.noesis.v1;

public final class FlinkEnrichmentServiceProto {
  private FlinkEnrichmentServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_AddedFieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_AddedFieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_BatchFlinkEnrichmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_FlinkHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_FlinkHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_FlinkHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_FlinkHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_FlinkHistoricalRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_FlinkHistoricalRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,datapower/noesis/v1/enrichment_service" +
      ".proto\022\023datapower.noesis.v1\032\034google/prot" +
      "obuf/struct.proto\032\"datapower/noesis/v1/s" +
      "ervices.proto\"\347\002\n\027FlinkEnrichmentRespons" +
      "e\022@\n\017enriched_record\030\001 \001(\0132\027.google.prot" +
      "obuf.StructR\016enrichedRecord\022`\n\014added_fie" +
      "lds\030\002 \003(\0132=.datapower.noesis.v1.FlinkEnr" +
      "ichmentResponse.AddedFieldsEntryR\013addedF" +
      "ields\022\026\n\006errors\030\003 \003(\tR\006errors\022,\n\022process" +
      "ing_time_ms\030\004 \001(\003R\020processingTimeMs\022\"\n\rf" +
      "link_task_id\030\005 \001(\tR\013flinkTaskId\032>\n\020Added" +
      "FieldsEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002" +
      " \001(\tR\005value:\0028\001\"|\n\033BatchFlinkEnrichmentR" +
      "equest\022B\n\010requests\030\001 \003(\0132&.datapower.noe" +
      "sis.v1.EnrichmentRequestR\010requests\022\031\n\010ba" +
      "tch_id\030\002 \001(\005R\007batchId\"\243\001\n\034BatchFlinkEnri" +
      "chmentResponse\022J\n\tresponses\030\001 \003(\0132,.data" +
      "power.noesis.v1.FlinkEnrichmentResponseR" +
      "\tresponses\0227\n\030total_processing_time_ms\030\002" +
      " \001(\003R\025totalProcessingTimeMs\"\274\001\n\023FlinkHis" +
      "toryRequest\022\024\n\005table\030\001 \001(\tR\005table\022\016\n\002id\030" +
      "\002 \001(\tR\002id\022\035\n\nstart_date\030\003 \001(\tR\tstartDate" +
      "\022\031\n\010end_date\030\004 \001(\tR\007endDate\022\026\n\006fields\030\005 " +
      "\003(\tR\006fields\022-\n\022include_watermarks\030\006 \001(\010R" +
      "\021includeWatermarks\"\226\001\n\024FlinkHistoryRespo" +
      "nse\022D\n\007records\030\001 \003(\0132*.datapower.noesis." +
      "v1.FlinkHistoricalRecordR\007records\022\024\n\005err" +
      "or\030\002 \001(\tR\005error\022\"\n\rquery_time_ms\030\003 \001(\003R\013" +
      "queryTimeMs\"\205\002\n\025FlinkHistoricalRecord\022+\n" +
      "\004data\030\001 \001(\0132\027.google.protobuf.StructR\004da" +
      "ta\022\035\n\nvalid_from\030\002 \001(\tR\tvalidFrom\022\031\n\010val" +
      "id_to\030\003 \001(\tR\007validTo\022\037\n\013change_type\030\004 \001(" +
      "\tR\nchangeType\022\035\n\nevent_time\030\005 \001(\003R\tevent" +
      "Time\022\'\n\017processing_time\030\006 \001(\003R\016processin" +
      "gTime\022\034\n\twatermark\030\007 \001(\tR\twatermark2\371\001\n\026" +
      "FlinkEnrichmentService\022d\n\014EnrichRecord\022&" +
      ".datapower.noesis.v1.EnrichmentRequest\032," +
      ".datapower.noesis.v1.FlinkEnrichmentResp" +
      "onse\022y\n\022BatchEnrichRecords\0220.datapower.n" +
      "oesis.v1.BatchFlinkEnrichmentRequest\0321.d" +
      "atapower.noesis.v1.BatchFlinkEnrichmentR" +
      "esponse2\250\002\n\023FlinkRawDataService\022[\n\nGetRo" +
      "wById\022%.datapower.noesis.v1.RowLookupReq" +
      "uest\032&.datapower.noesis.v1.RowLookupResp" +
      "onse\022Q\n\006Search\022\".datapower.noesis.v1.Sea" +
      "rchRequest\032#.datapower.noesis.v1.SearchR" +
      "esponse\022a\n\nGetHistory\022(.datapower.noesis" +
      ".v1.FlinkHistoryRequest\032).datapower.noes" +
      "is.v1.FlinkHistoryResponseB\210\001\n\023datapower" +
      ".noesis.v1B\033FlinkEnrichmentServiceProtoP" +
      "\001ZRgithub.com/data-power-io/noesis-proto" +
      "col/languages/go/datapower/noesis/v1;noe" +
      "sisv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          datapower.noesis.v1.Services.getDescriptor(),
        });
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_descriptor,
        new java.lang.String[] { "EnrichedRecord", "AddedFields", "Errors", "ProcessingTimeMs", "FlinkTaskId", });
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_AddedFieldsEntry_descriptor =
      internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_descriptor.getNestedTypes().get(0);
    internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_AddedFieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_FlinkEnrichmentResponse_AddedFieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_BatchFlinkEnrichmentRequest_descriptor,
        new java.lang.String[] { "Requests", "BatchId", });
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datapower_noesis_v1_BatchFlinkEnrichmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_BatchFlinkEnrichmentResponse_descriptor,
        new java.lang.String[] { "Responses", "TotalProcessingTimeMs", });
    internal_static_datapower_noesis_v1_FlinkHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datapower_noesis_v1_FlinkHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_FlinkHistoryRequest_descriptor,
        new java.lang.String[] { "Table", "Id", "StartDate", "EndDate", "Fields", "IncludeWatermarks", });
    internal_static_datapower_noesis_v1_FlinkHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datapower_noesis_v1_FlinkHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_FlinkHistoryResponse_descriptor,
        new java.lang.String[] { "Records", "Error", "QueryTimeMs", });
    internal_static_datapower_noesis_v1_FlinkHistoricalRecord_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datapower_noesis_v1_FlinkHistoricalRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_FlinkHistoricalRecord_descriptor,
        new java.lang.String[] { "Data", "ValidFrom", "ValidTo", "ChangeType", "EventTime", "ProcessingTime", "Watermark", });
    com.google.protobuf.StructProto.getDescriptor();
    datapower.noesis.v1.Services.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
