// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/services.proto

package datapower.noesis.v1;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_RowLookupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_RowLookupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_RowLookupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_RowLookupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_SearchRequest_FiltersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_SearchRequest_FiltersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_SearchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_SearchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_BatchLookupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_BatchLookupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_BatchLookupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_BatchLookupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_BatchLookupResponse_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_BatchLookupResponse_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_EnrichmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_EnrichmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_EnrichmentRequest_ContextEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_EnrichmentRequest_ContextEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_EnrichmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_EnrichmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_EnrichmentResponse_AddedFieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_EnrichmentResponse_AddedFieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_ValidationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_ValidationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_ValidationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_ValidationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_datapower_noesis_v1_ValidationError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_datapower_noesis_v1_ValidationError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"datapower/noesis/v1/services.proto\022\023da" +
      "tapower.noesis.v1\032\034google/protobuf/struc" +
      "t.proto\"P\n\020RowLookupRequest\022\024\n\005table\030\001 \001" +
      "(\tR\005table\022\016\n\002id\030\002 \001(\tR\002id\022\026\n\006fields\030\003 \003(" +
      "\tR\006fields\"l\n\021RowLookupResponse\022\024\n\005found\030" +
      "\001 \001(\010R\005found\022+\n\004data\030\002 \001(\0132\027.google.prot" +
      "obuf.StructR\004data\022\024\n\005error\030\003 \001(\tR\005error\"" +
      "\362\001\n\rSearchRequest\022\024\n\005table\030\001 \001(\tR\005table\022" +
      "I\n\007filters\030\002 \003(\0132/.datapower.noesis.v1.S" +
      "earchRequest.FiltersEntryR\007filters\022\024\n\005li" +
      "mit\030\003 \001(\005R\005limit\022\026\n\006offset\030\004 \001(\005R\006offset" +
      "\022\026\n\006fields\030\005 \003(\tR\006fields\032:\n\014FiltersEntry" +
      "\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value" +
      ":\0028\001\"z\n\016SearchResponse\0221\n\007results\030\001 \003(\0132" +
      "\027.google.protobuf.StructR\007results\022\037\n\013tot" +
      "al_count\030\002 \001(\005R\ntotalCount\022\024\n\005error\030\003 \001(" +
      "\tR\005error\"T\n\022BatchLookupRequest\022\024\n\005table\030" +
      "\001 \001(\tR\005table\022\020\n\003ids\030\002 \003(\tR\003ids\022\026\n\006fields" +
      "\030\003 \003(\tR\006fields\"\356\001\n\023BatchLookupResponse\022O" +
      "\n\007results\030\001 \003(\01325.datapower.noesis.v1.Ba" +
      "tchLookupResponse.ResultsEntryR\007results\022" +
      "\033\n\tnot_found\030\002 \003(\tR\010notFound\022\024\n\005error\030\003 " +
      "\001(\tR\005error\032S\n\014ResultsEntry\022\020\n\003key\030\001 \001(\tR" +
      "\003key\022-\n\005value\030\002 \001(\0132\027.google.protobuf.St" +
      "ructR\005value:\0028\001\"\220\002\n\021EnrichmentRequest\022\024\n" +
      "\005table\030\001 \001(\tR\005table\022/\n\006record\030\002 \001(\0132\027.go" +
      "ogle.protobuf.StructR\006record\022M\n\007context\030" +
      "\003 \003(\01323.datapower.noesis.v1.EnrichmentRe" +
      "quest.ContextEntryR\007context\022)\n\020requested" +
      "_fields\030\004 \003(\tR\017requestedFields\032:\n\014Contex" +
      "tEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR" +
      "\005value:\0028\001\"\211\002\n\022EnrichmentResponse\022@\n\017enr" +
      "iched_record\030\001 \001(\0132\027.google.protobuf.Str" +
      "uctR\016enrichedRecord\022[\n\014added_fields\030\002 \003(" +
      "\01328.datapower.noesis.v1.EnrichmentRespon" +
      "se.AddedFieldsEntryR\013addedFields\022\024\n\005erro" +
      "r\030\003 \001(\tR\005error\032>\n\020AddedFieldsEntry\022\020\n\003ke" +
      "y\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"p" +
      "\n\021ValidationRequest\022\024\n\005table\030\001 \001(\tR\005tabl" +
      "e\022/\n\006record\030\002 \001(\0132\027.google.protobuf.Stru" +
      "ctR\006record\022\024\n\005rules\030\003 \003(\tR\005rules\"h\n\022Vali" +
      "dationResponse\022\024\n\005valid\030\001 \001(\010R\005valid\022<\n\006" +
      "errors\030\002 \003(\0132$.datapower.noesis.v1.Valid" +
      "ationErrorR\006errors\"U\n\017ValidationError\022\024\n" +
      "\005field\030\001 \001(\tR\005field\022\022\n\004rule\030\002 \001(\tR\004rule\022" +
      "\030\n\007message\030\003 \001(\tR\007message2\242\002\n\016RawDataSer" +
      "vice\022[\n\nGetRowById\022%.datapower.noesis.v1" +
      ".RowLookupRequest\032&.datapower.noesis.v1." +
      "RowLookupResponse\022Q\n\006Search\022\".datapower." +
      "noesis.v1.SearchRequest\032#.datapower.noes" +
      "is.v1.SearchResponse\022`\n\013BatchLookup\022\'.da" +
      "tapower.noesis.v1.BatchLookupRequest\032(.d" +
      "atapower.noesis.v1.BatchLookupResponse2\327" +
      "\001\n\021EnrichmentService\022_\n\014EnrichRecord\022&.d" +
      "atapower.noesis.v1.EnrichmentRequest\032\'.d" +
      "atapower.noesis.v1.EnrichmentResponse\022a\n" +
      "\016ValidateRecord\022&.datapower.noesis.v1.Va" +
      "lidationRequest\032\'.datapower.noesis.v1.Va" +
      "lidationResponseBk\n\023datapower.noesis.v1P" +
      "\001ZRgithub.com/data-power-io/noesis-proto" +
      "col/languages/go/datapower/noesis/v1;noe" +
      "sisv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_datapower_noesis_v1_RowLookupRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_datapower_noesis_v1_RowLookupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_RowLookupRequest_descriptor,
        new java.lang.String[] { "Table", "Id", "Fields", });
    internal_static_datapower_noesis_v1_RowLookupResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_datapower_noesis_v1_RowLookupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_RowLookupResponse_descriptor,
        new java.lang.String[] { "Found", "Data", "Error", });
    internal_static_datapower_noesis_v1_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_datapower_noesis_v1_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_SearchRequest_descriptor,
        new java.lang.String[] { "Table", "Filters", "Limit", "Offset", "Fields", });
    internal_static_datapower_noesis_v1_SearchRequest_FiltersEntry_descriptor =
      internal_static_datapower_noesis_v1_SearchRequest_descriptor.getNestedTypes().get(0);
    internal_static_datapower_noesis_v1_SearchRequest_FiltersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_SearchRequest_FiltersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_datapower_noesis_v1_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_datapower_noesis_v1_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_SearchResponse_descriptor,
        new java.lang.String[] { "Results", "TotalCount", "Error", });
    internal_static_datapower_noesis_v1_BatchLookupRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_datapower_noesis_v1_BatchLookupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_BatchLookupRequest_descriptor,
        new java.lang.String[] { "Table", "Ids", "Fields", });
    internal_static_datapower_noesis_v1_BatchLookupResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_datapower_noesis_v1_BatchLookupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_BatchLookupResponse_descriptor,
        new java.lang.String[] { "Results", "NotFound", "Error", });
    internal_static_datapower_noesis_v1_BatchLookupResponse_ResultsEntry_descriptor =
      internal_static_datapower_noesis_v1_BatchLookupResponse_descriptor.getNestedTypes().get(0);
    internal_static_datapower_noesis_v1_BatchLookupResponse_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_BatchLookupResponse_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_datapower_noesis_v1_EnrichmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_datapower_noesis_v1_EnrichmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_EnrichmentRequest_descriptor,
        new java.lang.String[] { "Table", "Record", "Context", "RequestedFields", });
    internal_static_datapower_noesis_v1_EnrichmentRequest_ContextEntry_descriptor =
      internal_static_datapower_noesis_v1_EnrichmentRequest_descriptor.getNestedTypes().get(0);
    internal_static_datapower_noesis_v1_EnrichmentRequest_ContextEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_EnrichmentRequest_ContextEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_datapower_noesis_v1_EnrichmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_datapower_noesis_v1_EnrichmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_EnrichmentResponse_descriptor,
        new java.lang.String[] { "EnrichedRecord", "AddedFields", "Error", });
    internal_static_datapower_noesis_v1_EnrichmentResponse_AddedFieldsEntry_descriptor =
      internal_static_datapower_noesis_v1_EnrichmentResponse_descriptor.getNestedTypes().get(0);
    internal_static_datapower_noesis_v1_EnrichmentResponse_AddedFieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_EnrichmentResponse_AddedFieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_datapower_noesis_v1_ValidationRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_datapower_noesis_v1_ValidationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_ValidationRequest_descriptor,
        new java.lang.String[] { "Table", "Record", "Rules", });
    internal_static_datapower_noesis_v1_ValidationResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_datapower_noesis_v1_ValidationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_ValidationResponse_descriptor,
        new java.lang.String[] { "Valid", "Errors", });
    internal_static_datapower_noesis_v1_ValidationError_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_datapower_noesis_v1_ValidationError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_datapower_noesis_v1_ValidationError_descriptor,
        new java.lang.String[] { "Field", "Rule", "Message", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
