// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/sidecar.proto

package datapower.noesis.v1;

/**
 * Protobuf type {@code datapower.noesis.v1.SessionStats}
 */
public final class SessionStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datapower.noesis.v1.SessionStats)
    SessionStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SessionStats.newBuilder() to construct.
  private SessionStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SessionStats() {
    filePaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SessionStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_SessionStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_SessionStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datapower.noesis.v1.SessionStats.class, datapower.noesis.v1.SessionStats.Builder.class);
  }

  public static final int TOTAL_RECORDS_WRITTEN_FIELD_NUMBER = 1;
  private long totalRecordsWritten_ = 0L;
  /**
   * <code>int64 total_records_written = 1 [json_name = "totalRecordsWritten"];</code>
   * @return The totalRecordsWritten.
   */
  @java.lang.Override
  public long getTotalRecordsWritten() {
    return totalRecordsWritten_;
  }

  public static final int TOTAL_BYTES_WRITTEN_FIELD_NUMBER = 2;
  private long totalBytesWritten_ = 0L;
  /**
   * <code>int64 total_bytes_written = 2 [json_name = "totalBytesWritten"];</code>
   * @return The totalBytesWritten.
   */
  @java.lang.Override
  public long getTotalBytesWritten() {
    return totalBytesWritten_;
  }

  public static final int TOTAL_FILES_UPLOADED_FIELD_NUMBER = 3;
  private int totalFilesUploaded_ = 0;
  /**
   * <code>int32 total_files_uploaded = 3 [json_name = "totalFilesUploaded"];</code>
   * @return The totalFilesUploaded.
   */
  @java.lang.Override
  public int getTotalFilesUploaded() {
    return totalFilesUploaded_;
  }

  public static final int FILE_PATHS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList filePaths_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @return A list containing the filePaths.
   */
  public com.google.protobuf.ProtocolStringList
      getFilePathsList() {
    return filePaths_;
  }
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @return The count of filePaths.
   */
  public int getFilePathsCount() {
    return filePaths_.size();
  }
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @param index The index of the element to return.
   * @return The filePaths at the given index.
   */
  public java.lang.String getFilePaths(int index) {
    return filePaths_.get(index);
  }
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the filePaths at the given index.
   */
  public com.google.protobuf.ByteString
      getFilePathsBytes(int index) {
    return filePaths_.getByteString(index);
  }

  public static final int DURATION_MS_FIELD_NUMBER = 5;
  private long durationMs_ = 0L;
  /**
   * <pre>
   * Total session duration
   * </pre>
   *
   * <code>int64 duration_ms = 5 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  @java.lang.Override
  public long getDurationMs() {
    return durationMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalRecordsWritten_ != 0L) {
      output.writeInt64(1, totalRecordsWritten_);
    }
    if (totalBytesWritten_ != 0L) {
      output.writeInt64(2, totalBytesWritten_);
    }
    if (totalFilesUploaded_ != 0) {
      output.writeInt32(3, totalFilesUploaded_);
    }
    for (int i = 0; i < filePaths_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, filePaths_.getRaw(i));
    }
    if (durationMs_ != 0L) {
      output.writeInt64(5, durationMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalRecordsWritten_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, totalRecordsWritten_);
    }
    if (totalBytesWritten_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, totalBytesWritten_);
    }
    if (totalFilesUploaded_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalFilesUploaded_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < filePaths_.size(); i++) {
        dataSize += computeStringSizeNoTag(filePaths_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilePathsList().size();
    }
    if (durationMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, durationMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datapower.noesis.v1.SessionStats)) {
      return super.equals(obj);
    }
    datapower.noesis.v1.SessionStats other = (datapower.noesis.v1.SessionStats) obj;

    if (getTotalRecordsWritten()
        != other.getTotalRecordsWritten()) return false;
    if (getTotalBytesWritten()
        != other.getTotalBytesWritten()) return false;
    if (getTotalFilesUploaded()
        != other.getTotalFilesUploaded()) return false;
    if (!getFilePathsList()
        .equals(other.getFilePathsList())) return false;
    if (getDurationMs()
        != other.getDurationMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_RECORDS_WRITTEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalRecordsWritten());
    hash = (37 * hash) + TOTAL_BYTES_WRITTEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalBytesWritten());
    hash = (37 * hash) + TOTAL_FILES_UPLOADED_FIELD_NUMBER;
    hash = (53 * hash) + getTotalFilesUploaded();
    if (getFilePathsCount() > 0) {
      hash = (37 * hash) + FILE_PATHS_FIELD_NUMBER;
      hash = (53 * hash) + getFilePathsList().hashCode();
    }
    hash = (37 * hash) + DURATION_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDurationMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datapower.noesis.v1.SessionStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static datapower.noesis.v1.SessionStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static datapower.noesis.v1.SessionStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.SessionStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datapower.noesis.v1.SessionStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code datapower.noesis.v1.SessionStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datapower.noesis.v1.SessionStats)
      datapower.noesis.v1.SessionStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_SessionStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_SessionStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datapower.noesis.v1.SessionStats.class, datapower.noesis.v1.SessionStats.Builder.class);
    }

    // Construct using datapower.noesis.v1.SessionStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalRecordsWritten_ = 0L;
      totalBytesWritten_ = 0L;
      totalFilesUploaded_ = 0;
      filePaths_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      durationMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datapower.noesis.v1.SidecarOuterClass.internal_static_datapower_noesis_v1_SessionStats_descriptor;
    }

    @java.lang.Override
    public datapower.noesis.v1.SessionStats getDefaultInstanceForType() {
      return datapower.noesis.v1.SessionStats.getDefaultInstance();
    }

    @java.lang.Override
    public datapower.noesis.v1.SessionStats build() {
      datapower.noesis.v1.SessionStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public datapower.noesis.v1.SessionStats buildPartial() {
      datapower.noesis.v1.SessionStats result = new datapower.noesis.v1.SessionStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(datapower.noesis.v1.SessionStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalRecordsWritten_ = totalRecordsWritten_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalBytesWritten_ = totalBytesWritten_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalFilesUploaded_ = totalFilesUploaded_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        filePaths_.makeImmutable();
        result.filePaths_ = filePaths_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.durationMs_ = durationMs_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datapower.noesis.v1.SessionStats) {
        return mergeFrom((datapower.noesis.v1.SessionStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datapower.noesis.v1.SessionStats other) {
      if (other == datapower.noesis.v1.SessionStats.getDefaultInstance()) return this;
      if (other.getTotalRecordsWritten() != 0L) {
        setTotalRecordsWritten(other.getTotalRecordsWritten());
      }
      if (other.getTotalBytesWritten() != 0L) {
        setTotalBytesWritten(other.getTotalBytesWritten());
      }
      if (other.getTotalFilesUploaded() != 0) {
        setTotalFilesUploaded(other.getTotalFilesUploaded());
      }
      if (!other.filePaths_.isEmpty()) {
        if (filePaths_.isEmpty()) {
          filePaths_ = other.filePaths_;
          bitField0_ |= 0x00000008;
        } else {
          ensureFilePathsIsMutable();
          filePaths_.addAll(other.filePaths_);
        }
        onChanged();
      }
      if (other.getDurationMs() != 0L) {
        setDurationMs(other.getDurationMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              totalRecordsWritten_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              totalBytesWritten_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalFilesUploaded_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFilePathsIsMutable();
              filePaths_.add(s);
              break;
            } // case 34
            case 40: {
              durationMs_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long totalRecordsWritten_ ;
    /**
     * <code>int64 total_records_written = 1 [json_name = "totalRecordsWritten"];</code>
     * @return The totalRecordsWritten.
     */
    @java.lang.Override
    public long getTotalRecordsWritten() {
      return totalRecordsWritten_;
    }
    /**
     * <code>int64 total_records_written = 1 [json_name = "totalRecordsWritten"];</code>
     * @param value The totalRecordsWritten to set.
     * @return This builder for chaining.
     */
    public Builder setTotalRecordsWritten(long value) {

      totalRecordsWritten_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_records_written = 1 [json_name = "totalRecordsWritten"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalRecordsWritten() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totalRecordsWritten_ = 0L;
      onChanged();
      return this;
    }

    private long totalBytesWritten_ ;
    /**
     * <code>int64 total_bytes_written = 2 [json_name = "totalBytesWritten"];</code>
     * @return The totalBytesWritten.
     */
    @java.lang.Override
    public long getTotalBytesWritten() {
      return totalBytesWritten_;
    }
    /**
     * <code>int64 total_bytes_written = 2 [json_name = "totalBytesWritten"];</code>
     * @param value The totalBytesWritten to set.
     * @return This builder for chaining.
     */
    public Builder setTotalBytesWritten(long value) {

      totalBytesWritten_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_bytes_written = 2 [json_name = "totalBytesWritten"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalBytesWritten() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalBytesWritten_ = 0L;
      onChanged();
      return this;
    }

    private int totalFilesUploaded_ ;
    /**
     * <code>int32 total_files_uploaded = 3 [json_name = "totalFilesUploaded"];</code>
     * @return The totalFilesUploaded.
     */
    @java.lang.Override
    public int getTotalFilesUploaded() {
      return totalFilesUploaded_;
    }
    /**
     * <code>int32 total_files_uploaded = 3 [json_name = "totalFilesUploaded"];</code>
     * @param value The totalFilesUploaded to set.
     * @return This builder for chaining.
     */
    public Builder setTotalFilesUploaded(int value) {

      totalFilesUploaded_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_files_uploaded = 3 [json_name = "totalFilesUploaded"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalFilesUploaded() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalFilesUploaded_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList filePaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFilePathsIsMutable() {
      if (!filePaths_.isModifiable()) {
        filePaths_ = new com.google.protobuf.LazyStringArrayList(filePaths_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @return A list containing the filePaths.
     */
    public com.google.protobuf.ProtocolStringList
        getFilePathsList() {
      filePaths_.makeImmutable();
      return filePaths_;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @return The count of filePaths.
     */
    public int getFilePathsCount() {
      return filePaths_.size();
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param index The index of the element to return.
     * @return The filePaths at the given index.
     */
    public java.lang.String getFilePaths(int index) {
      return filePaths_.get(index);
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the filePaths at the given index.
     */
    public com.google.protobuf.ByteString
        getFilePathsBytes(int index) {
      return filePaths_.getByteString(index);
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param index The index to set the value at.
     * @param value The filePaths to set.
     * @return This builder for chaining.
     */
    public Builder setFilePaths(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilePathsIsMutable();
      filePaths_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param value The filePaths to add.
     * @return This builder for chaining.
     */
    public Builder addFilePaths(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilePathsIsMutable();
      filePaths_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param values The filePaths to add.
     * @return This builder for chaining.
     */
    public Builder addAllFilePaths(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilePathsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, filePaths_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFilePaths() {
      filePaths_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of uploaded file paths
     * </pre>
     *
     * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
     * @param value The bytes of the filePaths to add.
     * @return This builder for chaining.
     */
    public Builder addFilePathsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFilePathsIsMutable();
      filePaths_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long durationMs_ ;
    /**
     * <pre>
     * Total session duration
     * </pre>
     *
     * <code>int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @return The durationMs.
     */
    @java.lang.Override
    public long getDurationMs() {
      return durationMs_;
    }
    /**
     * <pre>
     * Total session duration
     * </pre>
     *
     * <code>int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @param value The durationMs to set.
     * @return This builder for chaining.
     */
    public Builder setDurationMs(long value) {

      durationMs_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total session duration
     * </pre>
     *
     * <code>int64 duration_ms = 5 [json_name = "durationMs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000010);
      durationMs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datapower.noesis.v1.SessionStats)
  }

  // @@protoc_insertion_point(class_scope:datapower.noesis.v1.SessionStats)
  private static final datapower.noesis.v1.SessionStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datapower.noesis.v1.SessionStats();
  }

  public static datapower.noesis.v1.SessionStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionStats>
      PARSER = new com.google.protobuf.AbstractParser<SessionStats>() {
    @java.lang.Override
    public SessionStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SessionStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public datapower.noesis.v1.SessionStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

