// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/sidecar.proto

package datapower.noesis.v1;

public interface SessionStatsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.SessionStats)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 total_records_written = 1 [json_name = "totalRecordsWritten"];</code>
   * @return The totalRecordsWritten.
   */
  long getTotalRecordsWritten();

  /**
   * <code>int64 total_bytes_written = 2 [json_name = "totalBytesWritten"];</code>
   * @return The totalBytesWritten.
   */
  long getTotalBytesWritten();

  /**
   * <code>int32 total_files_uploaded = 3 [json_name = "totalFilesUploaded"];</code>
   * @return The totalFilesUploaded.
   */
  int getTotalFilesUploaded();

  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @return A list containing the filePaths.
   */
  java.util.List<java.lang.String>
      getFilePathsList();
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @return The count of filePaths.
   */
  int getFilePathsCount();
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @param index The index of the element to return.
   * @return The filePaths at the given index.
   */
  java.lang.String getFilePaths(int index);
  /**
   * <pre>
   * List of uploaded file paths
   * </pre>
   *
   * <code>repeated string file_paths = 4 [json_name = "filePaths"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the filePaths at the given index.
   */
  com.google.protobuf.ByteString
      getFilePathsBytes(int index);

  /**
   * <pre>
   * Total session duration
   * </pre>
   *
   * <code>int64 duration_ms = 5 [json_name = "durationMs"];</code>
   * @return The durationMs.
   */
  long getDurationMs();
}
