// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/pipeline.proto

package datapower.noesis.v1;

public interface SinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.Sink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Alias used to reference this sink in the query
   * </pre>
   *
   * <code>string alias = 1 [json_name = "alias"];</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   * Alias used to reference this sink in the query
   * </pre>
   *
   * <code>string alias = 1 [json_name = "alias"];</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   * Type of sink (currently only "kafka_topic")
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Type of sink (currently only "kafka_topic")
   * </pre>
   *
   * <code>string type = 2 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * Topic name where transformed events will be written
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Topic name where transformed events will be written
   * </pre>
   *
   * <code>string name = 3 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional: Partitioning key for the sink topic
   * </pre>
   *
   * <code>string partition_key = 4 [json_name = "partitionKey"];</code>
   * @return The partitionKey.
   */
  java.lang.String getPartitionKey();
  /**
   * <pre>
   * Optional: Partitioning key for the sink topic
   * </pre>
   *
   * <code>string partition_key = 4 [json_name = "partitionKey"];</code>
   * @return The bytes for partitionKey.
   */
  com.google.protobuf.ByteString
      getPartitionKeyBytes();

  /**
   * <pre>
   * Optional: Serialization format (json, avro, protobuf)
   * </pre>
   *
   * <code>string format = 5 [json_name = "format"];</code>
   * @return The format.
   */
  java.lang.String getFormat();
  /**
   * <pre>
   * Optional: Serialization format (json, avro, protobuf)
   * </pre>
   *
   * <code>string format = 5 [json_name = "format"];</code>
   * @return The bytes for format.
   */
  com.google.protobuf.ByteString
      getFormatBytes();
}
