// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/connector.proto

package datapower.noesis.v1;

public interface StructValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:datapower.noesis.v1.StructValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .datapower.noesis.v1.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  int getFieldsCount();
  /**
   * <code>map&lt;string, .datapower.noesis.v1.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  boolean containsFields(
      java.lang.String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, datapower.noesis.v1.Value>
  getFields();
  /**
   * <code>map&lt;string, .datapower.noesis.v1.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  java.util.Map<java.lang.String, datapower.noesis.v1.Value>
  getFieldsMap();
  /**
   * <code>map&lt;string, .datapower.noesis.v1.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  /* nullable */
datapower.noesis.v1.Value getFieldsOrDefault(
      java.lang.String key,
      /* nullable */
datapower.noesis.v1.Value defaultValue);
  /**
   * <code>map&lt;string, .datapower.noesis.v1.Value&gt; fields = 1 [json_name = "fields"];</code>
   */
  datapower.noesis.v1.Value getFieldsOrThrow(
      java.lang.String key);
}
