// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datapower/noesis/v1/patch_events.proto

package datapower.noesis.v1;

/**
 * <pre>
 * TransformEventBatch is used for batch processing of events
 * Useful for bulk operations and optimization
 * </pre>
 *
 * Protobuf type {@code datapower.noesis.v1.TransformEventBatch}
 */
public final class TransformEventBatch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:datapower.noesis.v1.TransformEventBatch)
    TransformEventBatchOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TransformEventBatch.newBuilder() to construct.
  private TransformEventBatch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TransformEventBatch() {
    batchId_ = "";
    pipelineName_ = "";
    events_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TransformEventBatch();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return datapower.noesis.v1.PatchEvents.internal_static_datapower_noesis_v1_TransformEventBatch_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return datapower.noesis.v1.PatchEvents.internal_static_datapower_noesis_v1_TransformEventBatch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            datapower.noesis.v1.TransformEventBatch.class, datapower.noesis.v1.TransformEventBatch.Builder.class);
  }

  public static final int BATCH_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object batchId_ = "";
  /**
   * <pre>
   * Batch ID
   * </pre>
   *
   * <code>string batch_id = 1 [json_name = "batchId"];</code>
   * @return The batchId.
   */
  @java.lang.Override
  public java.lang.String getBatchId() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Batch ID
   * </pre>
   *
   * <code>string batch_id = 1 [json_name = "batchId"];</code>
   * @return The bytes for batchId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBatchIdBytes() {
    java.lang.Object ref = batchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PIPELINE_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pipelineName_ = "";
  /**
   * <pre>
   * Pipeline name
   * </pre>
   *
   * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
   * @return The pipelineName.
   */
  @java.lang.Override
  public java.lang.String getPipelineName() {
    java.lang.Object ref = pipelineName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pipelineName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pipeline name
   * </pre>
   *
   * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
   * @return The bytes for pipelineName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPipelineNameBytes() {
    java.lang.Object ref = pipelineName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pipelineName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENTS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<datapower.noesis.v1.TransformEvent> events_;
  /**
   * <pre>
   * All events in this batch
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
   */
  @java.lang.Override
  public java.util.List<datapower.noesis.v1.TransformEvent> getEventsList() {
    return events_;
  }
  /**
   * <pre>
   * All events in this batch
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends datapower.noesis.v1.TransformEventOrBuilder> 
      getEventsOrBuilderList() {
    return events_;
  }
  /**
   * <pre>
   * All events in this batch
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
   */
  @java.lang.Override
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <pre>
   * All events in this batch
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.TransformEvent getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <pre>
   * All events in this batch
   * </pre>
   *
   * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.TransformEventOrBuilder getEventsOrBuilder(
      int index) {
    return events_.get(index);
  }

  public static final int METADATA_FIELD_NUMBER = 4;
  private datapower.noesis.v1.BatchMetadata metadata_;
  /**
   * <pre>
   * Batch metadata
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <pre>
   * Batch metadata
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  @java.lang.Override
  public datapower.noesis.v1.BatchMetadata getMetadata() {
    return metadata_ == null ? datapower.noesis.v1.BatchMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <pre>
   * Batch metadata
   * </pre>
   *
   * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public datapower.noesis.v1.BatchMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? datapower.noesis.v1.BatchMetadata.getDefaultInstance() : metadata_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batchId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pipelineName_);
    }
    for (int i = 0; i < events_.size(); i++) {
      output.writeMessage(3, events_.get(i));
    }
    if (metadata_ != null) {
      output.writeMessage(4, getMetadata());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(batchId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batchId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pipelineName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pipelineName_);
    }
    for (int i = 0; i < events_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, events_.get(i));
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getMetadata());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof datapower.noesis.v1.TransformEventBatch)) {
      return super.equals(obj);
    }
    datapower.noesis.v1.TransformEventBatch other = (datapower.noesis.v1.TransformEventBatch) obj;

    if (!getBatchId()
        .equals(other.getBatchId())) return false;
    if (!getPipelineName()
        .equals(other.getPipelineName())) return false;
    if (!getEventsList()
        .equals(other.getEventsList())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBatchId().hashCode();
    hash = (37 * hash) + PIPELINE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPipelineName().hashCode();
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static datapower.noesis.v1.TransformEventBatch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static datapower.noesis.v1.TransformEventBatch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static datapower.noesis.v1.TransformEventBatch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(datapower.noesis.v1.TransformEventBatch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * TransformEventBatch is used for batch processing of events
   * Useful for bulk operations and optimization
   * </pre>
   *
   * Protobuf type {@code datapower.noesis.v1.TransformEventBatch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:datapower.noesis.v1.TransformEventBatch)
      datapower.noesis.v1.TransformEventBatchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return datapower.noesis.v1.PatchEvents.internal_static_datapower_noesis_v1_TransformEventBatch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return datapower.noesis.v1.PatchEvents.internal_static_datapower_noesis_v1_TransformEventBatch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              datapower.noesis.v1.TransformEventBatch.class, datapower.noesis.v1.TransformEventBatch.Builder.class);
    }

    // Construct using datapower.noesis.v1.TransformEventBatch.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      batchId_ = "";
      pipelineName_ = "";
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
      } else {
        events_ = null;
        eventsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return datapower.noesis.v1.PatchEvents.internal_static_datapower_noesis_v1_TransformEventBatch_descriptor;
    }

    @java.lang.Override
    public datapower.noesis.v1.TransformEventBatch getDefaultInstanceForType() {
      return datapower.noesis.v1.TransformEventBatch.getDefaultInstance();
    }

    @java.lang.Override
    public datapower.noesis.v1.TransformEventBatch build() {
      datapower.noesis.v1.TransformEventBatch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public datapower.noesis.v1.TransformEventBatch buildPartial() {
      datapower.noesis.v1.TransformEventBatch result = new datapower.noesis.v1.TransformEventBatch(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(datapower.noesis.v1.TransformEventBatch result) {
      if (eventsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.events_ = events_;
      } else {
        result.events_ = eventsBuilder_.build();
      }
    }

    private void buildPartial0(datapower.noesis.v1.TransformEventBatch result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.batchId_ = batchId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pipelineName_ = pipelineName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof datapower.noesis.v1.TransformEventBatch) {
        return mergeFrom((datapower.noesis.v1.TransformEventBatch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(datapower.noesis.v1.TransformEventBatch other) {
      if (other == datapower.noesis.v1.TransformEventBatch.getDefaultInstance()) return this;
      if (!other.getBatchId().isEmpty()) {
        batchId_ = other.batchId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getPipelineName().isEmpty()) {
        pipelineName_ = other.pipelineName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (eventsBuilder_ == null) {
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
      } else {
        if (!other.events_.isEmpty()) {
          if (eventsBuilder_.isEmpty()) {
            eventsBuilder_.dispose();
            eventsBuilder_ = null;
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000004);
            eventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventsFieldBuilder() : null;
          } else {
            eventsBuilder_.addAllMessages(other.events_);
          }
        }
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              batchId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              pipelineName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              datapower.noesis.v1.TransformEvent m =
                  input.readMessage(
                      datapower.noesis.v1.TransformEvent.parser(),
                      extensionRegistry);
              if (eventsBuilder_ == null) {
                ensureEventsIsMutable();
                events_.add(m);
              } else {
                eventsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object batchId_ = "";
    /**
     * <pre>
     * Batch ID
     * </pre>
     *
     * <code>string batch_id = 1 [json_name = "batchId"];</code>
     * @return The batchId.
     */
    public java.lang.String getBatchId() {
      java.lang.Object ref = batchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Batch ID
     * </pre>
     *
     * <code>string batch_id = 1 [json_name = "batchId"];</code>
     * @return The bytes for batchId.
     */
    public com.google.protobuf.ByteString
        getBatchIdBytes() {
      java.lang.Object ref = batchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Batch ID
     * </pre>
     *
     * <code>string batch_id = 1 [json_name = "batchId"];</code>
     * @param value The batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch ID
     * </pre>
     *
     * <code>string batch_id = 1 [json_name = "batchId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBatchId() {
      batchId_ = getDefaultInstance().getBatchId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch ID
     * </pre>
     *
     * <code>string batch_id = 1 [json_name = "batchId"];</code>
     * @param value The bytes for batchId to set.
     * @return This builder for chaining.
     */
    public Builder setBatchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      batchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object pipelineName_ = "";
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
     * @return The pipelineName.
     */
    public java.lang.String getPipelineName() {
      java.lang.Object ref = pipelineName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipelineName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
     * @return The bytes for pipelineName.
     */
    public com.google.protobuf.ByteString
        getPipelineNameBytes() {
      java.lang.Object ref = pipelineName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipelineName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
     * @param value The pipelineName to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pipelineName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPipelineName() {
      pipelineName_ = getDefaultInstance().getPipelineName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pipeline name
     * </pre>
     *
     * <code>string pipeline_name = 2 [json_name = "pipelineName"];</code>
     * @param value The bytes for pipelineName to set.
     * @return This builder for chaining.
     */
    public Builder setPipelineNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pipelineName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<datapower.noesis.v1.TransformEvent> events_ =
      java.util.Collections.emptyList();
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        events_ = new java.util.ArrayList<datapower.noesis.v1.TransformEvent>(events_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.TransformEvent, datapower.noesis.v1.TransformEvent.Builder, datapower.noesis.v1.TransformEventOrBuilder> eventsBuilder_;

    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public java.util.List<datapower.noesis.v1.TransformEvent> getEventsList() {
      if (eventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(events_);
      } else {
        return eventsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public int getEventsCount() {
      if (eventsBuilder_ == null) {
        return events_.size();
      } else {
        return eventsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public datapower.noesis.v1.TransformEvent getEvents(int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);
      } else {
        return eventsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder setEvents(
        int index, datapower.noesis.v1.TransformEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder setEvents(
        int index, datapower.noesis.v1.TransformEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder addEvents(datapower.noesis.v1.TransformEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder addEvents(
        int index, datapower.noesis.v1.TransformEvent value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(index, value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder addEvents(
        datapower.noesis.v1.TransformEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder addEvents(
        int index, datapower.noesis.v1.TransformEvent.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder addAllEvents(
        java.lang.Iterable<? extends datapower.noesis.v1.TransformEvent> values) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
      } else {
        eventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder clearEvents() {
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public Builder removeEvents(int index) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.remove(index);
        onChanged();
      } else {
        eventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public datapower.noesis.v1.TransformEvent.Builder getEventsBuilder(
        int index) {
      return getEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public datapower.noesis.v1.TransformEventOrBuilder getEventsOrBuilder(
        int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);  } else {
        return eventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public java.util.List<? extends datapower.noesis.v1.TransformEventOrBuilder> 
         getEventsOrBuilderList() {
      if (eventsBuilder_ != null) {
        return eventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(events_);
      }
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public datapower.noesis.v1.TransformEvent.Builder addEventsBuilder() {
      return getEventsFieldBuilder().addBuilder(
          datapower.noesis.v1.TransformEvent.getDefaultInstance());
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public datapower.noesis.v1.TransformEvent.Builder addEventsBuilder(
        int index) {
      return getEventsFieldBuilder().addBuilder(
          index, datapower.noesis.v1.TransformEvent.getDefaultInstance());
    }
    /**
     * <pre>
     * All events in this batch
     * </pre>
     *
     * <code>repeated .datapower.noesis.v1.TransformEvent events = 3 [json_name = "events"];</code>
     */
    public java.util.List<datapower.noesis.v1.TransformEvent.Builder> 
         getEventsBuilderList() {
      return getEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        datapower.noesis.v1.TransformEvent, datapower.noesis.v1.TransformEvent.Builder, datapower.noesis.v1.TransformEventOrBuilder> 
        getEventsFieldBuilder() {
      if (eventsBuilder_ == null) {
        eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            datapower.noesis.v1.TransformEvent, datapower.noesis.v1.TransformEvent.Builder, datapower.noesis.v1.TransformEventOrBuilder>(
                events_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        events_ = null;
      }
      return eventsBuilder_;
    }

    private datapower.noesis.v1.BatchMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.BatchMetadata, datapower.noesis.v1.BatchMetadata.Builder, datapower.noesis.v1.BatchMetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     * @return The metadata.
     */
    public datapower.noesis.v1.BatchMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? datapower.noesis.v1.BatchMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(datapower.noesis.v1.BatchMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public Builder setMetadata(
        datapower.noesis.v1.BatchMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public Builder mergeMetadata(datapower.noesis.v1.BatchMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          metadata_ != null &&
          metadata_ != datapower.noesis.v1.BatchMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000008);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public datapower.noesis.v1.BatchMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    public datapower.noesis.v1.BatchMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            datapower.noesis.v1.BatchMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <pre>
     * Batch metadata
     * </pre>
     *
     * <code>.datapower.noesis.v1.BatchMetadata metadata = 4 [json_name = "metadata"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        datapower.noesis.v1.BatchMetadata, datapower.noesis.v1.BatchMetadata.Builder, datapower.noesis.v1.BatchMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            datapower.noesis.v1.BatchMetadata, datapower.noesis.v1.BatchMetadata.Builder, datapower.noesis.v1.BatchMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:datapower.noesis.v1.TransformEventBatch)
  }

  // @@protoc_insertion_point(class_scope:datapower.noesis.v1.TransformEventBatch)
  private static final datapower.noesis.v1.TransformEventBatch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new datapower.noesis.v1.TransformEventBatch();
  }

  public static datapower.noesis.v1.TransformEventBatch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransformEventBatch>
      PARSER = new com.google.protobuf.AbstractParser<TransformEventBatch>() {
    @java.lang.Override
    public TransformEventBatch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransformEventBatch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransformEventBatch> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public datapower.noesis.v1.TransformEventBatch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

