name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for breaking change detection

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint proto files
        run: buf lint

      - name: Check for breaking changes
        if: github.event_name == 'pull_request'
        run: buf breaking --against https://github.com/${{ github.repository }}.git#branch=main

  generate-and-build:
    runs-on: ubuntu-latest
    needs: lint-and-breaking
    steps:
      - uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate code
        run: buf generate

      - name: Build Go module
        working-directory: languages/go
        run: |
          go mod tidy
          go build ./...

      - name: Test Go module
        working-directory: languages/go
        run: go test ./...

      - name: Build Java JAR
        working-directory: languages/java
        run: mvn clean compile test-compile

      - name: Upload generated code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: |
            languages/go/datapower/
            languages/java/src/
          retention-days: 7